"""URL construction helpers for the archives rules_flutter downloads.

Two independent origins, and the distinction matters when reading the rest of
this file:

  * **Engine artifacts** — prebuilt binaries (gen_snapshot, frontend_server,
    the patched SDK, per-platform engine libraries), hosted on Google Cloud
    Storage at
        https://storage.googleapis.com/flutter_infra_release/flutter/{engine_revision}/{artifact_path}
    and keyed by *engine revision*. Most of this file builds those paths.

  * **The framework source tarball** — GitHub's autogenerated archive of a
    release tag, keyed by *Flutter version*. One tarball serves every consumer
    that needs Flutter's own Dart source, and they differ only in which subtree
    they strip to:

      - `flutter_sdk_package` → `packages/<name>`, once per SDK package in the
        lock (flutter, flutter_test, flutter_driver, flutter_localizations,
        flutter_web_plugins),
      - `flutter_gen_l10n_repo` → `packages/flutter_tools`,
      - `flutter_dev_root_repo` → `packages` and the sky_engine tree.

    The URL is built here rather than restated in each of them.
"""

_GCS_BASE = "https://storage.googleapis.com/flutter_infra_release/flutter"

_SOURCE_TARBALL_TEMPLATE = "https://github.com/flutter/flutter/archive/refs/tags/{version}.tar.gz"

def flutter_source_tarball_url(flutter_version):
    """Constructs the download URL for the Flutter framework source tarball.

    GitHub generates this archive from the release tag on demand. Its bytes
    have been re-compressed before (notably GitHub's 2023 change), so every
    fetch is checksum-pinned against `source_sha256` in versions.bzl and a
    mismatch is a loud, intended failure rather than something to work around.

    Args:
        flutter_version: Flutter release tag (e.g. "3.47.2").

    Returns:
        The full HTTPS URL of the source tarball. Extracting it yields a
        single `flutter-{version}/` directory.
    """
    return _SOURCE_TARBALL_TEMPLATE.format(version = flutter_version)

def engine_artifact_url(engine_revision, artifact_path):
    """Constructs the full GCS download URL for a Flutter engine artifact.

    Args:
        engine_revision: The engine commit hash (40-char hex string).
        artifact_path: Path relative to the engine revision directory
            (e.g. "flutter_patched_sdk.zip", "darwin-x64/artifacts.zip").

    Returns:
        The full HTTPS URL to download the artifact.
    """
    return "{base}/{revision}/{path}".format(
        base = _GCS_BASE,
        revision = engine_revision,
        path = artifact_path,
    )

def dart_sdk_artifact_path(host_platform):
    """Returns the artifact path for the Flutter-bundled Dart SDK.

    Args:
        host_platform: Host platform string (e.g. "darwin-arm64", "linux-x64").

    Returns:
        Artifact path like "dart-sdk-darwin-arm64.zip".
    """
    return "dart-sdk-{platform}.zip".format(platform = host_platform)

def gen_snapshot_cross_artifact_path(target_platform, mode, host_platform):
    """Returns the artifact path for a cross-compile gen_snapshot archive.

    gen_snapshot is the AOT compiler. For cross-compilation (e.g. building
    Android on macOS), the binary is in a zip at:
        {target}-{mode}/{host}.zip

    Args:
        target_platform: Target platform (e.g. "android-arm64", "android-x64",
            "ios", "darwin-x64", "linux-x64").
        mode: Build mode ("profile" or "release").
        host_platform: Host platform where gen_snapshot runs
            (e.g. "darwin-x64", "linux-x64").

    Returns:
        Artifact path like "android-arm64-release/darwin-x64.zip".
    """
    return "{target}-{mode}/{host}.zip".format(
        target = target_platform,
        mode = mode,
        host = host_platform,
    )

def android_engine_artifact_path(android_arch, mode):
    """Returns the artifact path for the Android engine (flutter.jar).

    flutter.jar is a fat jar containing the Java embedding classes and
    the native libflutter.so for the target ABI.

    Args:
        android_arch: Android architecture (e.g. "arm64", "x64", "arm").
        mode: Build mode ("debug", "profile", "release").

    Returns:
        Artifact path like "android-arm64-release/artifacts.zip".
    """
    platform_dir = "android-{arch}".format(arch = android_arch)
    if mode != "debug":
        platform_dir = "{dir}-{mode}".format(dir = platform_dir, mode = mode)
    return "{dir}/artifacts.zip".format(dir = platform_dir)

def ios_engine_artifact_path(mode):
    """Returns the artifact path for the iOS engine (Flutter.xcframework).

    Args:
        mode: Build mode ("debug", "profile", "release").

    Returns:
        Artifact path like "ios-release/artifacts.zip".
    """
    platform_dir = "ios"
    if mode != "debug":
        platform_dir = "{dir}-{mode}".format(dir = platform_dir, mode = mode)
    return "{dir}/artifacts.zip".format(dir = platform_dir)

def host_artifacts_path(host_platform, mode = "debug"):
    """Returns the artifact path for host-platform tools archive.

    The host artifacts archive contains tools like gen_snapshot (for host),
    frontend_server, and other build tools.

    Args:
        host_platform: Host platform string (e.g. "darwin-x64", "linux-x64").
        mode: Build mode ("debug" or "release"). Debug archives contain the
            full toolset; release archives contain only gen_snapshot (product mode).

    Returns:
        Artifact path like "darwin-x64/artifacts.zip" or
        "darwin-x64-release/artifacts.zip".
    """
    platform_dir = host_platform
    if mode != "debug":
        platform_dir = "{dir}-{mode}".format(dir = platform_dir, mode = mode)
    return "{platform}/artifacts.zip".format(platform = platform_dir)

def desktop_engine_artifact_path(os, arch, mode):
    """Returns the artifact path for a desktop Flutter engine runtime library.

    Desktop engine artifacts contain the Flutter engine shared library needed
    to run Flutter applications on desktop platforms:
    - macOS: FlutterMacOS.framework.zip
    - Linux: linux-{arch}-flutter-gtk.zip
    - Windows: windows-{arch}-flutter.zip

    Args:
        os: Target OS ("macos", "linux", "windows").
        arch: Target architecture ("x64", "arm64").
        mode: Build mode ("debug", "profile", "release").

    Returns:
        Artifact path string, or None if the combination is not available.
    """

    # Map OS names to the platform directory prefix used by Flutter's GCS layout.
    os_prefix = {
        "macos": "darwin",
        "linux": "linux",
        "windows": "windows",
    }.get(os)
    if os_prefix == None:
        return None

    platform_dir = "{os}-{arch}".format(os = os_prefix, arch = arch)

    # macOS debug engine has no mode suffix (darwin-x64/framework.zip).
    # Linux and Windows desktop engines always include mode suffix, even for
    # debug (linux-x64-debug/, windows-x64-debug/).
    # See Flutter's LinuxEngineArtifacts.getBinaryDirs() and
    # WindowsEngineArtifacts.getBinaryDirs() in flutter_cache.dart.
    if os == "macos":
        if mode != "debug":
            platform_dir = "{dir}-{mode}".format(dir = platform_dir, mode = mode)
    else:
        platform_dir = "{dir}-{mode}".format(dir = platform_dir, mode = mode)

    if os == "macos":
        return "{dir}/FlutterMacOS.framework.zip".format(dir = platform_dir)
    elif os == "linux":
        return "{dir}/linux-{arch}-flutter-gtk.zip".format(dir = platform_dir, arch = arch)
    elif os == "windows":
        return "{dir}/windows-{arch}-flutter.zip".format(dir = platform_dir, arch = arch)
    return None
