"""Repository rule for desktop cross-platform toolchains.

Generates a flutter_toolchain that wires host tools (dart, frontend_server,
gen_snapshot, patched SDK) from the host repo with a desktop engine library
from a separate engine repo. Downloads nothing itself.

Desktop cross-toolchains only support debug/JIT mode — gen_snapshot cannot
cross-compile between desktop OSes for AOT.
"""

load(":engine_helpers.bzl", "dart_binary_name", "dartaotruntime_binary_name", "platform_to_arch", "platform_to_os")

def _flutter_desktop_cross_repo_impl(repository_ctx):
    host_platform = repository_ctx.attr.host_platform
    target_platform = repository_ctx.attr.target_platform
    flutter_version = repository_ctx.attr.flutter_version
    engine_revision = repository_ctx.attr.engine_revision
    host_repo_name = repository_ctx.attr.host_repo_name
    engine_repo_name = repository_ctx.attr.engine_repo_name
    engine_debug_repo_name = repository_ctx.attr.engine_debug_repo_name

    target_os = platform_to_os(target_platform)
    target_arch = platform_to_arch(target_platform)
    exe_suffix = ".exe" if host_platform.startswith("windows") else ""

    linux_sysroot_attr = ""
    sysroot_repo_name = repository_ctx.attr.sysroot_repo_name
    if sysroot_repo_name:
        linux_sysroot_attr = '    linux_sysroot = "@{}//:sysroot_files",'.format(sysroot_repo_name)

    # If a debug engine repo is provided, use select() to pick debug vs release
    # engine based on compilation mode. Otherwise, use the release engine always.
    if engine_debug_repo_name:
        engine_library_attr = """    engine_library = select({{
        "@rules_flutter//flutter/private:dbg": "@{debug_repo}//:engine_library",
        "//conditions:default": "@{release_repo}//:engine_library",
    }}),""".format(
            debug_repo = engine_debug_repo_name,
            release_repo = engine_repo_name,
        )
    else:
        engine_library_attr = '    engine_library = "@{}//:engine_library",'.format(engine_repo_name)

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        flutter_version = flutter_version,
        engine_revision = engine_revision,
        host_repo_name = host_repo_name,
        engine_library_attr = engine_library_attr,
        dart_bin = dart_binary_name(host_platform),
        dartaotruntime_bin = dartaotruntime_binary_name(host_platform),
        target_os = target_os,
        target_arch = target_arch,
        exe_suffix = exe_suffix,
        linux_sysroot_attr = linux_sysroot_attr,
    ))

_BUILD_TEMPLATE = """# Generated by flutter_desktop_cross_repo.bzl
load("@rules_flutter//flutter:toolchain.bzl", "flutter_toolchain")

flutter_toolchain(
    name = "flutter_toolchain",
    dart = "@{host_repo_name}//:dart-sdk/bin/{dart_bin}",
    dart_sdk = "@{host_repo_name}//:dart_sdk_files",
    dartaotruntime = "@{host_repo_name}//:dart-sdk/bin/{dartaotruntime_bin}",
{engine_library_attr}
    engine_revision = "{engine_revision}",
    frontend_server = "@{host_repo_name}//:host-tools/frontend_server_aot.dart.snapshot",
    gen_snapshot = "@{host_repo_name}//:host-tools/gen_snapshot{exe_suffix}",
    icu_data = "@{host_repo_name}//:host-tools/icudtl.dat",
    const_finder = "@{host_repo_name}//:font-subset-tools/const_finder.dart.snapshot",
    font_subset = "@{host_repo_name}//:font-subset-tools/font-subset{exe_suffix}",
    impellerc = "@{host_repo_name}//:host-tools/impellerc{exe_suffix}",
    material_icons_font = "@{host_repo_name}//:material-fonts/MaterialIcons-Regular.otf",
    vm_isolate_snapshot = "@{host_repo_name}//:host-tools/vm_isolate_snapshot.bin",
    isolate_snapshot = "@{host_repo_name}//:host-tools/isolate_snapshot.bin",
    shader_lib = "@{host_repo_name}//:shader_lib_files",
    patched_sdk = "@{host_repo_name}//:patched_sdk",
    platform_kernel_dill = "@{host_repo_name}//:patched-sdk/flutter_patched_sdk/platform_strong.dill",
    platform_kernel_dill_product = "@{host_repo_name}//:patched-sdk-product/flutter_patched_sdk_product/platform_strong.dill",
    target_arch = "{target_arch}",
    target_os = "{target_os}",
{linux_sysroot_attr}
    version = "{flutter_version}",
)
"""

flutter_desktop_cross_repo = repository_rule(
    _flutter_desktop_cross_repo_impl,
    doc = "Generates a desktop cross-platform toolchain wiring host tools with a target engine library.",
    attrs = {
        "flutter_version": attr.string(mandatory = True),
        "engine_revision": attr.string(mandatory = True),
        "host_platform": attr.string(mandatory = True),
        "target_platform": attr.string(mandatory = True),
        "host_repo_name": attr.string(mandatory = True, doc = "Name of the host platform's engine artifacts repo."),
        "engine_repo_name": attr.string(mandatory = True, doc = "Name of the desktop engine repo (release) for the target platform."),
        "engine_debug_repo_name": attr.string(doc = "Name of the debug desktop engine repo. When set, select() chooses debug vs release based on compilation mode."),
        "sysroot_repo_name": attr.string(doc = "Name of the Linux sysroot repo (for Linux targets only)."),
    },
)
