"""Repository rule for Android Flutter engine artifacts.

Downloads the Android engine (flutter.jar) which contains the Java
embedding classes (FlutterActivity, FlutterEngine, etc.) and the
native libflutter.so for the target ABI.

This is lazy — only fetched when an Android build target is used.
"""

load(":artifact_urls.bzl", "android_engine_artifact_path", "engine_artifact_url")

def _flutter_android_engine_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision
    android_arch = repository_ctx.attr.android_arch
    mode = repository_ctx.attr.mode

    artifact_path = android_engine_artifact_path(android_arch, mode)
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, artifact_path),
        sha256 = repository_ctx.attr.sha256 if repository_ctx.attr.sha256 else "",
    )

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        android_arch = android_arch,
    ))

_BUILD_TEMPLATE = """# Generated by flutter_android_engine_repo.bzl
#
# flutter.jar is a fat jar containing:
# - Java embedding classes (FlutterActivity, FlutterEngine, etc.)
# - Native libflutter.so for the target ABI at lib/<abi>/libflutter.so
#
# Use java_import in your BUILD file to consume it:
#   load("@rules_java//java:java_import.bzl", "java_import")
#   java_import(name = "flutter_embedding", jars = ["@flutter_android_engine_<arch>//:flutter.jar"])

exports_files(["flutter.jar"], visibility = ["//visibility:public"])
"""

flutter_android_engine_repo = repository_rule(
    _flutter_android_engine_repo_impl,
    doc = "Downloads the Android Flutter engine (flutter.jar) for a specific ABI.",
    attrs = {
        "engine_revision": attr.string(mandatory = True),
        "android_arch": attr.string(
            mandatory = True,
            doc = "Android architecture (arm64, x64, arm, x86, riscv64).",
        ),
        "mode": attr.string(
            default = "release",
            doc = "Build mode (debug, profile, release).",
        ),
        "sha256": attr.string(doc = "Expected SHA-256 of the archive."),
    },
)
