"""Repository rule for iOS Flutter engine artifacts.

Downloads both the release (AOT, device) and debug (JIT, simulator) iOS engines
(Flutter.xcframework) into a single repo, exposing one target per mode. This
mirrors the macOS engine repo (which carries both `engine_library` and
`engine_debug_library`): consumers reference the stable `@flutter_ios_engine`
name once in `use_repo` and the iOS macros `select()` between the two targets,
instead of having to enumerate a separate `@flutter_ios_engine_debug` repo.

This is lazy — only fetched when an iOS build target is used.
"""

load(":artifact_urls.bzl", "engine_artifact_url", "ios_engine_artifact_path")

def _flutter_ios_engine_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision

    # Release engine (AOT, device) at the repo root. The release archive also
    # carries the iOS gen_snapshot used by the macos->ios cross-compile toolchain.
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, ios_engine_artifact_path("release")),
        sha256 = repository_ctx.attr.release_sha256,
    )

    # Debug engine (JIT, simulator) under debug/ — its Flutter.xcframework would
    # otherwise collide with the release one at the repo root.
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, ios_engine_artifact_path("debug")),
        sha256 = repository_ctx.attr.debug_sha256,
        output = "debug",
    )

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

_BUILD_TEMPLATE = """# Generated by flutter_ios_engine_repo.bzl

# Release engine (AOT) — device builds (-c opt / default).
filegroup(
    name = "Flutter_xcframework",
    srcs = glob(["Flutter.xcframework/**"]),
    visibility = ["//visibility:public"],
)

# Debug engine (JIT) — simulator builds (-c dbg).
filegroup(
    name = "Flutter_xcframework_debug",
    srcs = glob(["debug/Flutter.xcframework/**"]),
    visibility = ["//visibility:public"],
)

exports_files(
    glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

flutter_ios_engine_repo = repository_rule(
    _flutter_ios_engine_repo_impl,
    doc = "Downloads the iOS Flutter engine (Flutter.xcframework) for both release and debug.",
    attrs = {
        "engine_revision": attr.string(mandatory = True),
        "release_sha256": attr.string(doc = "Expected SHA-256 of the release archive."),
        "debug_sha256": attr.string(doc = "Expected SHA-256 of the debug archive."),
    },
)
