"""Repository rule for downloading a Chromium sysroot for hermetic Linux builds.

Downloads the same Debian Bullseye sysroot that the Flutter engine was built
against, providing GTK3 headers and libraries without requiring host packages.

One repo per target architecture (amd64/arm64), shared across host platforms.
"""

load(":engine_helpers.bzl", "linux_multiarch_triple")

_SYSROOT_URL = "https://commondatastorage.googleapis.com/chrome-linux-sysroot/{sha256}"

# Map from our architecture names to the Debian architecture names used in
# the sysroot tarball's strip prefix.
_ARCH_TO_DEB = {
    "x64": "amd64",
    "arm64": "arm64",
}

def _flutter_linux_sysroot_repo_impl(repository_ctx):
    target_arch = repository_ctx.attr.target_arch
    sha256 = repository_ctx.attr.sha256

    deb_arch = _ARCH_TO_DEB.get(target_arch)
    if not deb_arch:
        fail("Unsupported sysroot architecture: {}".format(target_arch))

    repository_ctx.download_and_extract(
        url = _SYSROOT_URL.format(sha256 = sha256),
        sha256 = sha256,
        type = "tar.xz",
    )

    triple = linux_multiarch_triple(target_arch)
    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(triple = triple))

_BUILD_TEMPLATE = """# Generated by flutter_linux_sysroot_repo.bzl
filegroup(
    name = "sysroot_files",
    srcs = glob([
        "usr/include/gtk-3.0/**",
        "usr/include/glib-2.0/**",
        "usr/include/gio-unix-2.0/**",
        "usr/include/cairo/**",
        "usr/include/pango-1.0/**",
        "usr/include/atk-1.0/**",
        "usr/include/gdk-pixbuf-2.0/**",
        "usr/include/harfbuzz/**",
        "usr/include/freetype2/**",
        "usr/include/fribidi/**",
        "usr/include/at-spi2-atk/2.0/**",
        "usr/include/at-spi-2.0/**",
        "usr/include/dbus-1.0/**",
        "usr/include/pixman-1/**",
        "usr/include/uuid/**",
        "usr/include/libpng16/**",
        "usr/include/libmount/**",
        "usr/include/blkid/**",
        "usr/lib/{triple}/glib-2.0/**",
        "usr/lib/{triple}/dbus-1.0/**",
        "usr/lib/{triple}/*.so",
        "usr/lib/{triple}/*.so.*",
    ]),
    visibility = ["//visibility:public"],
)
"""

flutter_linux_sysroot_repo = repository_rule(
    _flutter_linux_sysroot_repo_impl,
    doc = "Downloads a Chromium sysroot for hermetic Linux desktop builds.",
    attrs = {
        "target_arch": attr.string(
            mandatory = True,
            doc = "Target architecture: x64 or arm64.",
            values = ["x64", "arm64"],
        ),
        "sha256": attr.string(
            mandatory = True,
            doc = "SHA-256 checksum (also the filename on the GCS bucket).",
        ),
    },
)
