"""The `sky_engine` package, which is how the analyzer resolves `dart:ui`.

Two different tools need the `dart:` libraries Flutter adds on top of the Dart
SDK, and they need them in two different forms. The compiler reads kernel:
`flutter_patched_sdk.zip` ships `platform_strong.dill`, and that is why
`flutter/extensions.bzl` deliberately drops `sky_engine` from the resolved pub
packages — the compile already has everything it needs. The analyzer reads
sources, and has no way to open a dill at all, so under that arrangement
`dart:ui` resolves for `flutter build` and fails for `dart analyze`.

What the analyzer looks for is narrow and entirely non-negotiable. It resolves
the literal package URI `package:sky_engine/_embedder.yaml` against the
project's `package_config.json`, and builds its SDK from the `embedded_libs`
map in that file (`analyzer`'s `ContextBuilderImpl._createSdk`). The package
must be named `sky_engine`, and the file must sit at `lib/_embedder.yaml` under
the package root; any other name and the lookup silently finds nothing, leaving
the host Dart SDK in place and every `dart:ui` reference undefined.

`sky_engine.zip` is published beside every other engine artifact, at the engine
revision already pinned in `versions.bzl`, and is ~1.5 MB. It gets its own
repository for the same reason the web SDK and the iOS engine do: it is an
engine artifact, fetched only when something actually analyzes Flutter code.
Hanging it off `flutter_dev_root` would have been cheaper to write and much
worse to use — that repository downloads the entire flutter/flutter tag
tarball, and it exists to be fetched only when `@rules_flutter//flutter:pub`
runs.

The generated package uses `dart_library`'s `resources`, which carries a
package's non-Dart `lib/` members and is newer than the `rules_dart 0.4.9` this
module pins. Nothing in rules_flutter references this repository yet, and Bazel
fetches it only on reference, so the pin is not yet a problem — but the analyze
targets that consume it cannot land until rules_dart ships that attribute and
MODULE.bazel moves to it.
"""

load(":artifact_urls.bzl", "engine_artifact_url")

_ROOT_BUILD_TEMPLATE = """# Generated by flutter_sky_engine_repo.bzl

alias(
    name = "sky_engine",
    actual = "//sky_engine",
    visibility = ["//visibility:public"],
)
"""

_PACKAGE_BUILD_TEMPLATE = """# Generated by flutter_sky_engine_repo.bzl
load("@rules_dart//dart:defs.bzl", "dart_library")

# `package_name` is not cosmetic and not derived: the analyzer resolves the
# literal `package:sky_engine/_embedder.yaml`, so this exact name is what makes
# the lookup hit. The remainder glob carries `_embedder.yaml` alongside
# `_internal/allowed_experiments.json` and `fix_data/fix_dart_ui.yaml` — the
# package's non-Dart members, listed by exclusion so a future artifact adding
# one more does not quietly ship a package with a hole in it.
dart_library(
    name = "sky_engine",
    srcs = glob(["lib/**/*.dart"]),
    package_name = "sky_engine",
    resources = glob(
        ["lib/**"],
        exclude = ["lib/**/*.dart"],
    ),
    visibility = ["//visibility:public"],
)
"""

def _flutter_sky_engine_repo_impl(repository_ctx):
    # Extracted at the repository root rather than under an `output` directory,
    # because the archive already nests everything one level under
    # `sky_engine/` — which is exactly the package root the analyzer wants, and
    # naming it twice would only bury it deeper. (The archive also carries a
    # stray top-level `LICENSE.zip_old_location.md`, which is why this does not
    # use `stripPrefix`: stripping would silently drop it.)
    repository_ctx.download_and_extract(
        url = engine_artifact_url(repository_ctx.attr.engine_revision, "sky_engine.zip"),
        sha256 = repository_ctx.attr.sha256,
    )

    # The Bazel package has to sit at `sky_engine/`, not at the repository
    # root: `dart_library` derives its `lib_root` from the label, and requires
    # every source to live under `<lib_root>/lib/`. Declared at the root, the
    # sources would be at `sky_engine/lib/...` against a `lib_root` expecting
    # `lib/...`, and the rule rejects that outright.
    repository_ctx.file("sky_engine/BUILD.bazel", _PACKAGE_BUILD_TEMPLATE)

    # …which would leave consumers writing `@flutter_sky_engine//sky_engine`,
    # naming the package twice. The alias buys back the obvious label.
    repository_ctx.file("BUILD.bazel", _ROOT_BUILD_TEMPLATE)

flutter_sky_engine_repo = repository_rule(
    _flutter_sky_engine_repo_impl,
    doc = "Downloads the `sky_engine` package, whose `lib/_embedder.yaml` is how the analyzer resolves `dart:ui` and the rest of Flutter's `dart:` libraries.",
    attrs = {
        "engine_revision": attr.string(
            mandatory = True,
            doc = "The engine commit hash the artifact is published under.",
        ),
        "sha256": attr.string(
            doc = "Expected SHA-256 of `sky_engine.zip`.",
        ),
    },
)
