"""Repository rule for Android Flutter engine artifacts.

Downloads the Android engine (flutter.jar) which contains the Java
embedding classes (FlutterActivity, FlutterEngine, etc.) and the
native libflutter.so for the target ABI. Both the release (AOT) and debug
(JIT) jars for an ABI live in one repo, so consumers reference a single
`flutter_android_engine_<abi>` repo and the `flutter_android_engine` macro
select()s between its two targets — mirroring the macOS and iOS engine repos.

This is lazy — only fetched when an Android build target is used.
"""

load(":artifact_urls.bzl", "android_engine_artifact_path", "engine_artifact_url")

def _flutter_android_engine_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision
    android_arch = repository_ctx.attr.android_arch

    # Release engine (AOT) at the repo root.
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, android_engine_artifact_path(android_arch, "release")),
        sha256 = repository_ctx.attr.release_sha256,
    )

    # Debug engine (JIT) under debug/ — its flutter.jar would otherwise collide
    # with the release one at the repo root.
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, android_engine_artifact_path(android_arch, "debug")),
        sha256 = repository_ctx.attr.debug_sha256,
        output = "debug",
    )

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

_BUILD_TEMPLATE = """# Generated by flutter_android_engine_repo.bzl
#
# flutter.jar is a fat jar containing:
# - Java embedding classes (FlutterActivity, FlutterEngine, etc.)
# - Native libflutter.so for the target ABI at lib/<abi>/libflutter.so
#
# Release (AOT) is `flutter.jar`; debug (JIT) is `debug/flutter.jar`. The
# flutter_android_engine macro select()s between them by compilation mode.

exports_files(
    ["flutter.jar", "debug/flutter.jar"],
    visibility = ["//visibility:public"],
)
"""

flutter_android_engine_repo = repository_rule(
    _flutter_android_engine_repo_impl,
    doc = "Downloads the Android Flutter engine (flutter.jar) for a specific ABI, both release and debug.",
    attrs = {
        "engine_revision": attr.string(mandatory = True),
        "android_arch": attr.string(
            mandatory = True,
            doc = "Android architecture (arm64, x64, arm, x86, riscv64).",
        ),
        "release_sha256": attr.string(doc = "Expected SHA-256 of the release archive."),
        "debug_sha256": attr.string(doc = "Expected SHA-256 of the debug archive."),
    },
)
