"""Repository rule for the Flutter web SDK.

Downloads flutter-web-sdk.zip which contains the platform dill files
needed for web builds (dart2wasm_platform.dill, dart2js_platform.dill).

Also downloads the Dart SDK for this host so that the web SDK's
libraries.json can resolve its `include` references to the base
Dart SDK libraries (dart:core, dart:async, etc.).
"""

load(":artifact_urls.bzl", "dart_sdk_artifact_path", "engine_artifact_url")

def _detect_host_platform(repository_ctx):
    """Detect the host platform string (e.g. 'darwin-arm64', 'linux-x64')."""
    os_name = repository_ctx.os.name
    arch = repository_ctx.os.arch

    if "mac" in os_name:
        os_prefix = "darwin"
    elif "linux" in os_name:
        os_prefix = "linux"
    elif "win" in os_name:
        os_prefix = "windows"
    else:
        fail("Unsupported host OS: %s" % os_name)

    if arch == "aarch64" or arch == "arm64":
        arch_suffix = "arm64"
    elif arch == "x86_64" or arch == "amd64":
        arch_suffix = "x64"
    else:
        fail("Unsupported host architecture: %s" % arch)

    return os_prefix + "-" + arch_suffix

def _flutter_web_sdk_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision

    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, "flutter-web-sdk.zip"),
        sha256 = repository_ctx.attr.sha256 if repository_ctx.attr.sha256 else "",
        output = "web-sdk",
    )

    # The web SDK's libraries.json references ../dart-sdk/lib/libraries.json
    # via an "include" directive. Download the Dart SDK so that path resolves
    # correctly in the Bazel sandbox.
    host_platform = _detect_host_platform(repository_ctx)
    dart_sdk_zip = dart_sdk_artifact_path(host_platform)
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, dart_sdk_zip),
        sha256 = "",
        stripPrefix = "dart-sdk",
        output = "dart-sdk",
    )

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

_BUILD_TEMPLATE = """# Generated by flutter_web_sdk_repo.bzl

filegroup(
    name = "web_sdk",
    srcs = glob(["web-sdk/**"]) + glob(["dart-sdk/lib/**"]),
    visibility = ["//visibility:public"],
)

exports_files(
    glob(["web-sdk/**"]) + glob(["dart-sdk/**"]),
    visibility = ["//visibility:public"],
)
"""

flutter_web_sdk_repo = repository_rule(
    _flutter_web_sdk_repo_impl,
    doc = "Downloads the Flutter web SDK (dart2wasm/dart2js platform dills) and supporting Dart SDK.",
    attrs = {
        "engine_revision": attr.string(mandatory = True),
        "sha256": attr.string(doc = "Expected SHA-256 of flutter-web-sdk.zip."),
    },
)
