"""Repository rule for Flutter cross-compilation toolchains.

Downloads the cross-compiling gen_snapshot and generates a flutter_toolchain
that references the host repo for dart, frontend_server, and patched SDK.

For iOS, the gen_snapshot is bundled inside the iOS engine artifact
(ios-release/artifacts.zip) — pass gen_snapshot_label pointing at the iOS
engine repo's gen_snapshot_arm64 instead of downloading a separate one.
"""

load(":artifact_urls.bzl", "engine_artifact_url", "gen_snapshot_cross_artifact_path")
load(":engine_helpers.bzl", "dart_binary_name", "dartaotruntime_binary_name", "gen_snapshot_host_platform", "platform_to_arch", "platform_to_os")

def _flutter_cross_compilation_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision
    host_platform = repository_ctx.attr.host_platform
    target_platform = repository_ctx.attr.target_platform
    flutter_version = repository_ctx.attr.flutter_version
    host_repo_name = repository_ctx.attr.host_repo_name

    if repository_ctx.attr.gen_snapshot_label:
        # Caller provided an explicit gen_snapshot label (e.g. from the iOS
        # engine repo). No download needed.
        gen_snapshot_label = repository_ctx.attr.gen_snapshot_label
    else:
        # Android and similar: download a target-specific gen_snapshot.
        artifact_host = gen_snapshot_host_platform(host_platform)
        artifact_path = gen_snapshot_cross_artifact_path(target_platform, "release", artifact_host)
        repository_ctx.download_and_extract(
            url = engine_artifact_url(engine_revision, artifact_path),
            sha256 = repository_ctx.attr.gen_snapshot_sha256 if repository_ctx.attr.gen_snapshot_sha256 else "",
        )
        gen_snapshot_label = ":gen_snapshot"

    # Generate BUILD.bazel referencing host repo for shared artifacts.
    exe_suffix = ".exe" if host_platform.startswith("windows") else ""
    build_content = _BUILD_TEMPLATE.format(
        flutter_version = flutter_version,
        engine_revision = engine_revision,
        host_repo_name = host_repo_name,
        dart_bin = dart_binary_name(host_platform),
        dartaotruntime_bin = dartaotruntime_binary_name(host_platform),
        target_os = platform_to_os(target_platform),
        target_arch = platform_to_arch(target_platform),
        gen_snapshot_label = gen_snapshot_label,
        exe_suffix = exe_suffix,
    )

    # Only export local gen_snapshot if we downloaded one.
    if not repository_ctx.attr.gen_snapshot_label:
        build_content = 'exports_files(["gen_snapshot"], visibility = ["//visibility:public"])\n\n' + build_content

    repository_ctx.file("BUILD.bazel", "# Generated by flutter_cross_repo.bzl\n" + build_content)

_BUILD_TEMPLATE = """load("@rules_flutter//flutter:toolchain.bzl", "flutter_toolchain")

flutter_toolchain(
    name = "flutter_toolchain",
    dart = "@{host_repo_name}//:dart-sdk/bin/{dart_bin}",
    dart_sdk = "@{host_repo_name}//:dart_sdk_files",
    dartaotruntime = "@{host_repo_name}//:dart-sdk/bin/{dartaotruntime_bin}",
    engine_revision = "{engine_revision}",
    frontend_server = "@{host_repo_name}//:host-tools/frontend_server_aot.dart.snapshot",
    gen_snapshot = "{gen_snapshot_label}",
    icu_data = "@{host_repo_name}//:host-tools/icudtl.dat",
    const_finder = "@{host_repo_name}//:font-subset-tools/const_finder.dart.snapshot",
    font_subset = "@{host_repo_name}//:font-subset-tools/font-subset{exe_suffix}",
    impellerc = "@{host_repo_name}//:host-tools/impellerc{exe_suffix}",
    material_icons_font = "@{host_repo_name}//:material-fonts/MaterialIcons-Regular.otf",
    vm_isolate_snapshot = "@{host_repo_name}//:host-tools/vm_isolate_snapshot.bin",
    isolate_snapshot = "@{host_repo_name}//:host-tools/isolate_snapshot.bin",
    shader_lib = "@{host_repo_name}//:shader_lib_files",
    patched_sdk = "@{host_repo_name}//:patched_sdk",
    platform_kernel_dill = "@{host_repo_name}//:patched-sdk/flutter_patched_sdk/platform_strong.dill",
    platform_kernel_dill_product = "@{host_repo_name}//:patched-sdk-product/flutter_patched_sdk_product/platform_strong.dill",
    target_arch = "{target_arch}",
    target_os = "{target_os}",
    version = "{flutter_version}",
)
"""

flutter_cross_compilation_repo = repository_rule(
    _flutter_cross_compilation_repo_impl,
    doc = "Downloads cross-compiling gen_snapshot and creates a toolchain referencing the host repo.",
    attrs = {
        "flutter_version": attr.string(mandatory = True),
        "engine_revision": attr.string(mandatory = True),
        "host_platform": attr.string(mandatory = True),
        "target_platform": attr.string(mandatory = True),
        "host_repo_name": attr.string(mandatory = True, doc = "Name of the host platform's engine artifacts repo."),
        "gen_snapshot_sha256": attr.string(doc = "SHA-256 of the gen_snapshot archive."),
        "gen_snapshot_label": attr.string(
            doc = "Explicit label for gen_snapshot binary from another repo (e.g. iOS engine repo). " +
                  "When set, no gen_snapshot is downloaded.",
        ),
    },
)
