"""Repository rule for downloading a desktop Flutter engine library.

Downloads the engine shared library for a specific desktop target platform
(e.g. libflutter_linux_gtk.so for Linux x64). This is a separate lazy repo
so it's only fetched when a cross-platform desktop build is actually used.

One repo per unique target platform, shared across hosts.
"""

load(":artifact_urls.bzl", "desktop_engine_artifact_path", "engine_artifact_url")
load(":engine_helpers.bzl", "engine_filegroup_for_os", "extract_macos_inner_framework")

def _flutter_desktop_engine_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision
    target_os = repository_ctx.attr.target_os
    target_arch = repository_ctx.attr.target_arch
    mode = repository_ctx.attr.mode

    artifact_path = desktop_engine_artifact_path(target_os, target_arch, mode)
    if not artifact_path:
        fail("No desktop engine artifact for {}-{}-{}".format(target_os, target_arch, mode))

    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, artifact_path),
        sha256 = repository_ctx.attr.sha256 if repository_ctx.attr.sha256 else "",
        output = "engine",
    )

    if target_os == "macos":
        extract_macos_inner_framework(repository_ctx)

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        engine_filegroup = engine_filegroup_for_os(target_os),
    ))

_BUILD_TEMPLATE = """# Generated by flutter_desktop_engine_repo.bzl
{engine_filegroup}
"""

flutter_desktop_engine_repo = repository_rule(
    _flutter_desktop_engine_repo_impl,
    doc = "Downloads a desktop Flutter engine library for cross-platform builds.",
    attrs = {
        "engine_revision": attr.string(mandatory = True),
        "target_os": attr.string(mandatory = True, doc = "Target OS: macos, linux, or windows."),
        "target_arch": attr.string(mandatory = True, doc = "Target architecture: x64 or arm64."),
        "mode": attr.string(default = "release", doc = "Build mode: debug, profile, or release."),
        "sha256": attr.string(doc = "Expected SHA-256 of the engine archive."),
    },
)
