"""Repository rule for macOS Flutter engine alias.

Creates a lightweight repo that aliases to the host platform's engine_library
(FlutterMacOS.framework) from the host artifacts repo. Exposes both release
and debug engines so that flutter_macos_engine() can select() between them.
Detects host arch at repo-rule time so users can reference a stable
`@flutter_macos_engine` name instead of the host-specific `@flutter_darwin-{arch}`.
"""

def _flutter_macos_engine_repo_impl(repository_ctx):
    # Detect host architecture at repo-rule time.
    result = repository_ctx.execute(["uname", "-m"])
    machine = result.stdout.strip()
    if machine == "arm64" or machine == "aarch64":
        host_arch = "arm64"
    else:
        host_arch = "x64"

    host_repo = repository_ctx.attr.user_repository_name + "_darwin-" + host_arch

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        host_repo = host_repo,
    ))

_BUILD_TEMPLATE = """# Generated by flutter_macos_engine_repo.bzl
# Aliases to the host platform's FlutterMacOS.framework engine libraries.

alias(
    name = "engine_library",
    actual = "@{host_repo}//:engine_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "engine_debug_library",
    actual = "@{host_repo}//:engine_debug_library",
    visibility = ["//visibility:public"],
)
"""

flutter_macos_engine_repo = repository_rule(
    _flutter_macos_engine_repo_impl,
    doc = "Creates an alias repo for the macOS Flutter engine (FlutterMacOS.framework).",
    attrs = {
        "user_repository_name": attr.string(
            doc = "Base name for Flutter repos (e.g. 'flutter').",
            mandatory = True,
        ),
    },
)
