"""Repository rule for iOS Flutter engine artifacts.

Downloads the iOS engine (Flutter.xcframework) which contains the
Flutter engine for device and simulator architectures.

This is lazy — only fetched when an iOS build target is used.
"""

load(":artifact_urls.bzl", "engine_artifact_url", "ios_engine_artifact_path")

def _flutter_ios_engine_repo_impl(repository_ctx):
    engine_revision = repository_ctx.attr.engine_revision
    mode = repository_ctx.attr.mode

    artifact_path = ios_engine_artifact_path(mode)
    repository_ctx.download_and_extract(
        url = engine_artifact_url(engine_revision, artifact_path),
        sha256 = repository_ctx.attr.sha256 if repository_ctx.attr.sha256 else "",
    )

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

_BUILD_TEMPLATE = """# Generated by flutter_ios_engine_repo.bzl

filegroup(
    name = "Flutter_xcframework",
    srcs = glob(["Flutter.xcframework/**"]),
    visibility = ["//visibility:public"],
)

# Device-only framework (arm64).
filegroup(
    name = "Flutter_framework_device",
    srcs = glob(["Flutter.xcframework/ios-arm64/Flutter.framework/**"]),
    visibility = ["//visibility:public"],
)

# Simulator framework (arm64 + x86_64 universal).
filegroup(
    name = "Flutter_framework_simulator",
    srcs = glob(["Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/**"]),
    visibility = ["//visibility:public"],
)

exports_files(
    glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

flutter_ios_engine_repo = repository_rule(
    _flutter_ios_engine_repo_impl,
    doc = "Downloads the iOS Flutter engine (Flutter.xcframework).",
    attrs = {
        "engine_revision": attr.string(mandatory = True),
        "mode": attr.string(
            default = "release",
            doc = "Build mode (debug, profile, release).",
        ),
        "sha256": attr.string(doc = "Expected SHA-256 of the archive."),
    },
)
