"""Create a repository to hold the toolchains.

This follows guidance here:
https://docs.bazel.build/versions/main/skylark/deploying.html#registering-toolchains
"
Note that in order to resolve toolchains in the analysis phase
Bazel needs to analyze all toolchain targets that are registered.
Bazel will not need to analyze all targets referenced by toolchain.toolchain attribute.
If in order to register toolchains you need to perform complex computation in the repository,
consider splitting the repository with toolchain targets
from the repository with <LANG>_toolchain targets.
"
The "complex computation" in our case is downloading large engine artifacts.
This guidance tells us how to avoid that: we put the toolchain targets in the alias repository
with only the toolchain attribute pointing into the platform-specific repositories.
"""

# Host platforms on which Flutter builds can run.
# Keys are platform strings used in Flutter artifact URLs.
HOST_PLATFORMS = {
    "darwin-arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
        os = "macos",
        arch = "arm64",
    ),
    "darwin-x64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
        os = "macos",
        arch = "x64",
    ),
    "linux-x64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
        os = "linux",
        arch = "x64",
    ),
    "linux-arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
        os = "linux",
        arch = "arm64",
    ),
    "windows-x64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
        os = "windows",
        arch = "x64",
    ),
}

# Cross-compilation target platforms.
# For each (host, target) pair, a toolchain is registered that runs on the
# host and produces output for the target.
TARGET_PLATFORMS = {
    "android-arm64": struct(
        compatible_with = [
            "@platforms//os:android",
            "@platforms//cpu:aarch64",
        ],
    ),
    "android-x64": struct(
        compatible_with = [
            "@platforms//os:android",
            "@platforms//cpu:x86_64",
        ],
    ),
    "ios-arm64": struct(
        compatible_with = [
            "@platforms//os:ios",
            "@platforms//cpu:aarch64",
        ],
    ),
}

# Desktop cross-platform pairs: host → list of desktop targets.
# Desktop targets ARE host platforms (they use HOST_PLATFORMS for constraints).
# These only support debug/JIT mode — gen_snapshot cannot cross-compile between
# desktop OSes for AOT.
DESKTOP_CROSS_PAIRS = {
    "darwin-arm64": ["linux-x64", "windows-x64"],
    "darwin-x64": ["linux-x64", "windows-x64"],
    "linux-x64": ["darwin-x64", "windows-x64"],
    "linux-arm64": ["darwin-x64", "windows-x64"],
    "windows-x64": ["darwin-x64", "linux-x64"],
}

# Which (host, target) cross-compilation pairs are supported.
CROSS_COMPILATION_PAIRS = {
    "darwin-arm64": ["android-arm64", "android-x64", "ios-arm64"],
    "darwin-x64": ["android-arm64", "android-x64", "ios-arm64"],
    "linux-x64": ["android-arm64", "android-x64"],
    "linux-arm64": ["android-arm64", "android-x64"],
    "windows-x64": ["android-arm64", "android-x64"],
}

def _flutter_toolchains_repo_impl(repository_ctx):
    build_content = """# Generated by toolchains_repo.bzl
#
# These can be registered via register_toolchains() or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the flutter_register_toolchains macro
# so you don't normally need to interact with these targets.

"""

    # Native (host == target) toolchains.
    for [platform, meta] in HOST_PLATFORMS.items():
        build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    target_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:flutter_toolchain",
    toolchain_type = "@rules_flutter//flutter:toolchain_type",
    visibility = ["//visibility:public"],
)
""".format(
            platform = platform,
            user_repository_name = repository_ctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Cross-compilation toolchains.
    for [host_platform, targets] in CROSS_COMPILATION_PAIRS.items():
        host_meta = HOST_PLATFORMS[host_platform]
        for target_platform in targets:
            target_meta = TARGET_PLATFORMS[target_platform]
            build_content += """
toolchain(
    name = "{host}_to_{target}_toolchain",
    exec_compatible_with = {exec_compatible_with},
    target_compatible_with = {target_compatible_with},
    toolchain = "@{user_repository_name}_cross_{host}_{target}//:flutter_toolchain",
    toolchain_type = "@rules_flutter//flutter:toolchain_type",
    visibility = ["//visibility:public"],
)
""".format(
                host = host_platform,
                target = target_platform,
                user_repository_name = repository_ctx.attr.user_repository_name,
                exec_compatible_with = host_meta.compatible_with,
                target_compatible_with = target_meta.compatible_with,
            )

    # Desktop cross-platform toolchains (debug only).
    for [host_platform, targets] in DESKTOP_CROSS_PAIRS.items():
        host_meta = HOST_PLATFORMS[host_platform]
        for target_platform in targets:
            target_meta = HOST_PLATFORMS[target_platform]
            build_content += """
toolchain(
    name = "{host}_to_{target}_desktop_toolchain",
    exec_compatible_with = {exec_compatible_with},
    target_compatible_with = {target_compatible_with},
    toolchain = "@{user_repository_name}_desktop_cross_{host}_{target}//:flutter_toolchain",
    toolchain_type = "@rules_flutter//flutter:toolchain_type",
    visibility = ["//visibility:public"],
)
""".format(
                host = host_platform,
                target = target_platform,
                user_repository_name = repository_ctx.attr.user_repository_name,
                exec_compatible_with = host_meta.compatible_with,
                target_compatible_with = target_meta.compatible_with,
            )

    repository_ctx.file("BUILD.bazel", build_content)

flutter_toolchains_repo = repository_rule(
    _flutter_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for all created repos"),
    },
)
