/// HTTP server for DDC-compiled web modules during development.
///
/// Implements DWDS's [AssetReader] interface and integrates DWDS for
/// VM service protocol support (hot reload, hot restart, debugging).
///
/// Serves: flutter_bootstrap.js (the build's, substituted for the dev loop),
/// main.dart.js (DDC bootstrap), DDC modules, dart_sdk.js, CanvasKit,
/// user web assets, and DWDS endpoints.
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:dwds/dwds.dart';
import 'package:http_multi_server/http_multi_server.dart';
import 'package:package_config/package_config.dart' as pkg;
import 'package:path/path.dart' as p;
import 'package:shelf/shelf.dart' as shelf;
import 'package:shelf/shelf_io.dart' as shelf_io;

import 'dev_tool_exception.dart';
import 'logging.dart';
import 'toolchain_info.dart';
import 'web_bootstrap.dart';
import 'web_options.dart';

export 'web_options.dart' show crossOriginIsolationHeaders;

/// Where this file's warnings and errors go.
///
/// Through the logger rather than straight to stderr so a `LOG_FORMAT=json`
/// consumer gets records it can parse, like every other diagnostic the tool
/// emits.
final _logger = Logger('dev_tool.web_module_server');

/// The one MIME table for everything the web dev loop serves.
///
/// Both [WebModuleServer] (DDC dev mode) and [StaticWebServer] (WASM /
/// production JS mode) answer from this table, so a file can never be typed
/// differently depending on which mode served it — a script typed
/// `application/octet-stream` by one route is a script the browser refuses
/// to execute, and the failure looks like a bug in the app.
///
/// Every entry is a type observed in real build output or generated by this
/// tool. `map` and `metadata` are the DDC compiler's source maps and module
/// metadata — JSON the debugger reads. Extensions absent from the table are
/// served as `application/octet-stream` deliberately, not as an accident of
/// a missed case: everything else a built bundle contains (`.bin` asset
/// manifests, `.frag` shaders, `.symbols`, `NOTICES.Z`) is fetched by the
/// engine, which never inspects the type. The types the browser *does*
/// enforce — scripts, wasm, html, css, fonts — are all named.
String contentTypeFor(String path) {
  final ext = p.extension(path).replaceFirst('.', '');
  return switch (ext) {
    'html' => 'text/html',
    'js' || 'mjs' => 'application/javascript',
    'wasm' => 'application/wasm',
    'json' => 'application/json',
    'css' => 'text/css',
    'png' => 'image/png',
    'ico' => 'image/x-icon',
    'otf' => 'font/otf',
    'txt' => 'text/plain',
    'map' || 'metadata' => 'application/json',
    _ => 'application/octet-stream',
  };
}

/// How many ephemeral ports a wildcard may draw before giving up.
///
/// `HttpMultiServer._loopback`'s own number, for the same search: it re-draws
/// up to five times when a port turns out to be free on one loopback family
/// and held on the other. Five consecutive intercepted draws is not bad luck —
/// it means something on this host is answering across the ephemeral range —
/// and that is when saying so is the useful answer.
const _maxPortDraws = 5;

/// Bind the one HTTP server both web servers serve from.
///
/// The response headers are set on the server's `defaultResponseHeaders`
/// rather than by shelf middleware, which is what upstream does
/// (`web_asset_server.dart`) and is the stronger of the two mechanisms here:
///
///  * Only defaults can *remove* a header dart:io adds by itself. dart:io
///    sends `X-Frame-Options: SAMEORIGIN` on every response, which forbids
///    embedding the app in an iframe; upstream removes it and so does this.
///    Middleware could never have taken it off.
///  * shelf writes a response's own headers with `set`, so they overwrite
///    these defaults key by key. A `--web-header Content-Type=…` therefore
///    cannot retype an asset out from under the browser, where middleware
///    applied after the handler would have.
///  * shelf's own 500 for a handler that threw never passes through
///    middleware, and does carry the defaults.
///
/// A named `--web-port` that cannot be taken is reported with the port in it,
/// because the whole point of naming a port is that something else is expected
/// to find the server there. Moving onto a different port would answer a
/// question nobody asked. `--web-port 0` is the opposite question — "any free
/// port" — and is searched for, up to [_maxPortDraws] draws.
Future<HttpServer> bindWebServer(
  WebServerOptions options,
  shelf.Handler handler,
) async {
  // A named port is one draw: it never moves, because something is expected to
  // find the server where it was named. `--web-port 0` is a search — "any free
  // port" — and a port whose traffic the kernel hands to somebody else is not
  // free. `HttpMultiServer._loopback` searches the same way for the same
  // reason, one family over; the only difference here is where the collision
  // becomes visible, since a wildcard bind cannot be refused.
  final draws = options.port == 0 ? _maxPortDraws : 1;
  for (var draw = 1; ; draw++) {
    try {
      return await _bindOneServer(options, handler);
    } on _InterceptedPort catch (e) {
      if (draw == draws) throw DevToolException(e.explain(options, draws));
    }
  }
}

/// One attempt: bind, dress, and — for a wildcard — confirm it is reached.
///
/// Throws [_InterceptedPort] when the port this bound is one it does not own;
/// every other failure throws what it is.
Future<HttpServer> _bindOneServer(
  WebServerOptions options,
  shelf.Handler handler,
) async {
  final HttpServer server;
  try {
    server = await _bindEveryAddressOfTheHost(options);
  } on SocketException catch (e) {
    throw DevToolException(
      'Cannot serve the app on ${options.hostname}:${options.port}: '
      '${e.osError ?? e}.\n'
      '${options.port == 0 ? 'No port could be bound at all, which is a '
                'problem with this host rather than with the run.' : 'Free port '
                '${options.port}, or pass a different --web-port. Nothing else '
                'is chosen for you: something is expected to find the server '
                'where you named it.'}',
    );
  }

  // Anything past this point owns the bound socket: a throw here has to give
  // it back, or the port stays held by a server nobody has a handle to — and
  // with `--web-port` that is the one port the next attempt needs.
  try {
    // dart:io's own default, and the reason a Flutter web app served by this
    // tool could not be embedded in an iframe. Removed as upstream removes
    // it. A run that wants it back can say so: `--web-header
    // X-Frame-Options=SAMEORIGIN`.
    server.defaultResponseHeaders.remove('x-frame-options', 'SAMEORIGIN');
    if (options.crossOriginIsolation) {
      crossOriginIsolationHeaders.forEach(server.defaultResponseHeaders.set);
    }
    // Last, so a `--web-header` naming something this tool also sets is the
    // one that survives — except the isolation headers, which
    // `WebOptions.resolve` refuses outright rather than letting either side
    // win quietly.
    options.headers.forEach((name, value) {
      try {
        server.defaultResponseHeaders.set(name, value);
      } catch (e) {
        // `dart:io` validates several header names and values itself — a
        // malformed `Date`, an illegal character in a name. Reported with the
        // flag and the pair in it; the raw HttpException names neither.
        throw DevToolException(
          'Cannot serve with --web-header $name=$value: $e',
        );
      }
    });
    // A wildcard bind is the one bind that can succeed without owning the
    // port, so it is the one that has to be asked. Every other hostname here
    // binds a specific address, and a specific address already held is a bind
    // the kernel refuses on every platform this runs on. There is nothing left
    // for a check to find there, and a check that no test can make fail is not
    // a check.
    if (options.hostname == anyHostname) {
      final probe = _ReachabilityProbe();
      shelf_io.serveRequests(server, probe.wrap(handler));
      await probe.confirmThisServerIsReached(options, server);
    } else {
      shelf_io.serveRequests(server, handler);
    }
  } catch (_) {
    await server.close(force: true);
    rethrow;
  }

  return server;
}

/// A request only this server can answer, used to confirm it is the server the
/// published URL actually reaches.
///
/// `--web-hostname any` binds a wildcard, and a wildcard bind is allowed to
/// succeed on a port another process already holds on one *specific* address.
/// The kernel then routes every connection to that address to the more
/// specific socket, so this server starts, prints its URL, and never receives
/// a request — with not even a failed bind to say so. That is not hypothetical:
/// `adb` keeps dozens of listening sockets on 127.0.0.1 in the ephemeral range,
/// and answers a connection by closing it without a byte.
///
/// Nothing about the bind can reveal that, so the server is asked instead: one
/// request per address the published URL resolves to, for a path only this
/// instance knows. Whatever else might hold the port can accept the connection
/// and can answer 200 — it cannot produce the nonce.
///
/// A failure here is what a `--web-port 0` run answers by drawing another
/// port, which is the same search `HttpMultiServer._loopback` runs for
/// `localhost`. A *named* port never moves; it fails naming itself.
///
/// What this proves is bounded, deliberately: it is the state at startup. A
/// process that takes a specific address on this port *later* still wins the
/// traffic from then on, and no arrangement of binds available here prevents
/// that — holding the specific addresses alongside the wildcard is refused
/// outright by Linux, which is the platform where the whole interception is
/// impossible anyway.
class _ReachabilityProbe {
  /// The path this instance answers, random so that nothing else listening on
  /// the port can answer it by coincidence and no bundle asset is shadowed by
  /// it. Answered only while the check is running.
  static final _random = Random.secure();
  final String _nonce = List.generate(
    16,
    (_) => _random.nextInt(256).toRadixString(16).padLeft(2, '0'),
  ).join();

  bool _answering = true;

  /// [inner] with this instance's one reserved path in front of it.
  shelf.Handler wrap(shelf.Handler inner) => (shelf.Request request) {
    if (_answering && request.url.path == _nonce) {
      return shelf.Response.ok(_nonce);
    }
    return inner(request);
  };

  /// Throw unless every address the published URL names reaches this server.
  ///
  /// Every address it names, with none dropped for belonging to a family this
  /// server did not bind. What this server binds is decided by a ::1 *bind*
  /// (`HttpMultiServer.supportsIPv6` picks the IPv4 wildcard when that fails),
  /// while what this check dials is decided by the *resolver* — two different
  /// tests, which a host could in principle answer differently. On every
  /// platform this runs on, none does:
  ///
  ///  * macOS: ::1 binds, so `any` is the dual-stack `::` wildcard, which
  ///    carries IPv4 too. The IPv4 wildcard is never the one chosen.
  ///  * Linux with no IPv6: the resolver has already dropped the family —
  ///    `InternetAddress.lookup('localhost')` returns 127.0.0.1 alone, so
  ///    there is nothing for a filter to remove.
  ///  * Windows: ::1 binds even with IPv6 disabled as far as Windows allows,
  ///    because ::1 stays on the loopback pseudo-interface regardless — so the
  ///    IPv4 wildcard is not chosen there either, and in that state the
  ///    resolver returns 127.0.0.1 alone exactly as Linux does.
  ///
  /// `getaddrinfo` does not agree with itself across languages: `python3`'s,
  /// called with `flags=0`, returns both families on a Linux host where Dart
  /// returns one. Dart matches the `AI_ADDRCONFIG`-filtered answer.
  Future<void> confirmThisServerIsReached(
    WebServerOptions options,
    HttpServer server,
  ) async {
    final port = server.port;
    final published = options.baseUri(port);
    // `displayHost` and not `hostname`: `any` is not a name anything resolves,
    // and the URL this run prints and opens a browser on says `localhost`.
    // That name is the promise being checked.
    final resolved = await InternetAddress.lookup(options.displayHost);
    for (final address in resolved) {
      final String answer;
      try {
        answer = await _fetch(
          published.replace(host: address.address, path: '/$_nonce'),
          options,
        );
      } catch (e) {
        throw _InterceptedPort(port, address, 'the request failed: $e');
      }
      if (answer != _nonce) {
        throw _InterceptedPort(port, address, 'something else answered it');
      }
    }
    _answering = false;
  }

  /// GET [url] and read it to the end.
  ///
  /// A self-signed certificate is accepted here: this run generated it, and
  /// the nonce — which no interloper can produce — is what identifies the
  /// server, not the certificate.
  Future<String> _fetch(Uri url, WebServerOptions options) async {
    final client = HttpClient();
    if (options.isSecure) {
      client.badCertificateCallback = (_, __, ___) => true;
    }
    try {
      final response = await (await client.getUrl(url)).close();
      return await response.transform(utf8.decoder).join();
    } finally {
      client.close(force: true);
    }
  }
}

/// A port a wildcard bind took and does not own.
///
/// Its own type rather than a [DevToolException] because it is the one failure
/// a `--web-port 0` run answers by drawing again: everything else that can go
/// wrong between bind and serve — an unusable certificate, a header `dart:io`
/// refuses — fails the same way on every port, and retrying it would report
/// the wrong cause five draws later.
class _InterceptedPort implements Exception {
  final int port;
  final InternetAddress address;

  /// What the server saw when it asked for itself.
  final String observed;

  const _InterceptedPort(this.port, this.address, this.observed);

  /// Why this run cannot be served, after [draws] of them.
  String explain(WebServerOptions options, int draws) =>
      'Cannot serve the app on --web-hostname $anyHostname: this run bound '
      'port $port on every interface, but ${options.baseUri(port)} over '
      '${address.address} does not reach it — $observed.\n'
      'Either something else already holds that port on that address — a '
      'wildcard bind is allowed to sit alongside a more specific listener, and '
      'the kernel hands that listener the connection — or nothing this run '
      'bound is listening there. Neither shows up as a failed bind, so this '
      'server would have started, printed its URL and never received a '
      'request.\n'
      '${draws == 1 ? 'Free port $port, or pass a different --web-port. '
                'Nothing else is chosen for you: something is expected to find the '
                'server where you named it.' : 'All $draws ports this run drew went '
                'the same way, so this is not one unlucky port: something on this '
                'host is answering across the ephemeral range. Name a port it does '
                'not hold with --web-port.'}';
}

/// Bind every socket the host in [options] stands for.
///
/// The URL this server publishes names a *host*, and `localhost` is not one
/// address: it is 127.0.0.1 and ::1. A client resolving that name chooses
/// between the two families itself, so a server that binds one of them is
/// reachable by only half its own URL — and the other half belongs to whatever
/// else on the machine happens to hold that port number on the family this
/// server left free.
///
/// That is how a dev run gets silently intercepted. `adb` keeps dozens of
/// listening sockets on 127.0.0.1 in the ephemeral range, roughly one port in
/// every four hundred. A server bound to ::1 that draws one of those numbers
/// hands every `localhost` client that picks IPv4 — Chrome included — to adb,
/// which accepts the connection and closes it without a byte. The page never
/// loads, and the DDC dev loop treats a browser that has not connected *yet* as
/// normal, so nothing reports it.
///
/// So the loopback is bound on both families, through the package the Dart
/// ecosystem's servers use for it. With `--web-port 0` that means searching
/// for a port free on both, which is what makes a collision a non-event; a
/// *named* port still fails naming it, including in the case that otherwise
/// looks like success — the port held on one family only.
///
/// [anyHostname] binds one dual-stack wildcard, covering both families for the
/// same reason the loopback does — the URL it publishes says `localhost`
/// ([WebServerOptions.displayHost]), because `any` is not a name a browser
/// resolves. Binding `0.0.0.0` would leave ::1 — half of its own URL — to
/// whatever else wanted it, which is the loopback defect one family over.
///
/// That is a deliberate widening of the flag: `any` answers on every
/// address of every interface rather than every IPv4 address, matching what
/// `flutter run` binds for the same flag and what the Dart ecosystem's servers
/// mean by "any". The exposure the flag already carries — the app and its
/// sources, on every network this host is attached to — is the same set of
/// networks, reached over both families instead of one.
///
/// One socket rather than a wildcard plus the specific loopbacks, which would
/// let the kernel refuse a squatted port at bind time: holding a specific
/// address alongside a wildcard on one port is permitted by BSD and refused
/// outright by Linux, so it cannot be what this does. What the wildcard cannot
/// learn at bind time, [_ReachabilityProbe] asks for after it.
///
/// Any other hostname binds the one address it resolves to: unambiguous when
/// it is written as an address, and carrying the same exposure when it is a
/// name with more than one behind it.
Future<HttpServer> _bindEveryAddressOfTheHost(WebServerOptions options) async {
  final context = options.isSecure ? _securityContext(options) : null;

  if (options.hostname == defaultHostname || options.hostname == anyHostname) {
    // `HttpMultiServer` reads both names itself: `localhost` is the pair of
    // loopback addresses, `any` is the dual-stack wildcard where the host has
    // IPv6 and the IPv4 one where it does not.
    return context == null
        ? HttpMultiServer.bind(options.hostname, options.port)
        : HttpMultiServer.bindSecure(options.hostname, options.port, context);
  }

  final InternetAddress address;
  try {
    address = (await InternetAddress.lookup(options.hostname)).first;
  } on SocketException catch (e) {
    throw DevToolException(
      'Cannot serve the app on --web-hostname ${options.hostname}: that '
      'name does not resolve on this host (${e.osError ?? e}).\n'
      'Use an address this machine has, or "any" for every interface.',
    );
  }
  return context == null
      ? HttpServer.bind(address, options.port)
      : HttpServer.bindSecure(address, options.port, context);
}

/// The TLS context for a server [options] says is secure.
///
/// Both paths are read here rather than at bind time so an unreadable
/// certificate is reported as one. `bindSecure` would otherwise surface it as
/// a bare `TlsException` or `FileSystemException` naming neither flag.
SecurityContext _securityContext(WebServerOptions options) {
  final context = SecurityContext();
  try {
    context.useCertificateChain(options.tlsCertPath!);
  } catch (e) {
    throw DevToolException(
      'Cannot serve over TLS: --web-tls-cert-path '
      '${options.tlsCertPath} could not be used as a certificate chain '
      '($e).',
    );
  }
  try {
    context.usePrivateKey(options.tlsCertKeyPath!);
  } catch (e) {
    throw DevToolException(
      'Cannot serve over TLS: --web-tls-cert-key-path '
      '${options.tlsCertKeyPath} could not be used as the private key for '
      '${options.tlsCertPath} ($e).',
    );
  }
  return context;
}

/// Serve the file at [requestPath] resolved inside [root].
///
/// 404 for a file that is not there — and for a path that resolves outside
/// [root], which no legitimate page request produces. `dart:io`'s HTTP
/// server already collapses `..` segments (encoded or not) before a handler
/// runs, so today no wire request can reach the check; it states the
/// contract explicitly rather than inheriting it from transport behavior.
shelf.Response serveFileWithin(String root, String requestPath) {
  final filePath = p.normalize(p.join(root, requestPath));
  if (!p.isWithin(root, filePath)) {
    return shelf.Response.notFound('File not found: $requestPath');
  }
  return _serveFile(filePath);
}

/// Serve the file at [filePath], typed from the one MIME table.
shelf.Response _serveFile(String filePath) {
  final file = File(filePath);
  if (!file.existsSync()) {
    return shelf.Response.notFound('File not found: $filePath');
  }
  return shelf.Response.ok(
    file.openRead(),
    headers: {'content-type': contentTypeFor(filePath)},
  );
}

/// Serves a built web bundle directory — WASM and production JS mode.
///
/// The static counterpart of [WebModuleServer]: no DWDS, no modules, just the
/// files the build wrote. Same MIME table ([contentTypeFor]) and same
/// isolation headers ([crossOriginIsolation]), by construction.
class StaticWebServer {
  /// The bundle directory to serve (e.g. `bazel-bin/app_wasm_web/`).
  final String rootPath;

  /// Where to bind, what to serve it over, and what headers to add. The same
  /// value the DDC module server is built from, so a serving flag cannot mean
  /// one thing for a DDC run and nothing at all for a WASM one.
  final WebServerOptions options;

  HttpServer? _server;

  StaticWebServer({required this.rootPath, required this.options});

  /// The underlying HTTP server, once started.
  ///
  /// Exposed so a launch can hand it to the instance that owns its lifetime.
  HttpServer? get server => _server;

  /// The base URL of the running server.
  Uri? get uri => _server == null ? null : options.baseUri(_server!.port);

  /// Bind where [options] say and start serving.
  Future<Uri> start() async {
    _server = await bindWebServer(options, _handle);
    return uri!;
  }

  /// Stop the HTTP server.
  Future<void> stop() async {
    await _server?.close();
    _server = null;
  }

  shelf.Response _handle(shelf.Request request) {
    final path = request.url.path.isEmpty ? 'index.html' : request.url.path;
    return serveFileWithin(rootPath, path);
  }
}

/// Serves DDC-compiled modules and static assets for web dev mode.
///
/// Implements [AssetReader] so DWDS can resolve sources, source maps,
/// and metadata for debugging and hot reload.
class WebModuleServer implements AssetReader {
  final WebToolchainPaths webToolchain;

  /// The build output directory (e.g. `bazel-bin/app_wasm_web/`).
  final String buildOutputDir;

  /// The synthetic entrypoint filename (just `main.dart`, not a full path).
  final String entrypointFilename;

  /// The file served at `/flutter_bootstrap.js`, from the build's dev config.
  ///
  /// The build substitutes this target's `bootstrap_js` template with the DDC
  /// build config a dev run compiles under — so a page booted here runs the
  /// same loader the bundle ships, carrying the same `web_defines`, against
  /// DDC's output instead of dart2wasm's. Read per request rather than cached:
  /// a `--watch` rebuild rewrites it when the template or a define changes,
  /// and the built index.html beside it is served from disk the same way.
  final String flutterBootstrapJsPath;

  /// Workspace root (for dart source lookups by DWDS).
  final String? workspaceRoot;

  /// Path to package_config.json (for DWDS package URI resolution).
  final String? packageConfigPath;

  /// Dart binary from the Flutter toolchain. DWDS launches its Dart
  /// Development Service with it rather than probing `Platform.executable`,
  /// which under Bazel is this AOT binary and cannot serve as a Dart SDK.
  final String dartExecutable;

  /// DDC's `nativeNonNullAsserts`, as the build set it.
  ///
  /// The dev loop generates `main_module.bootstrap.js` itself rather than
  /// serving the build's, so this is the one place the build's answer can
  /// reach the page.
  final bool nativeNullAssertions;

  /// Where to bind, what to serve it over, and what headers to add.
  final WebServerOptions options;

  /// Cached parsed package config for source resolution.
  pkg.PackageConfig? _packageConfig;

  /// Server paths whose source lookup already failed and was reported.
  ///
  /// DWDS asks for the same source on every debugger view, and the conditions
  /// that break a lookup — an unreadable package config, chiefly — break every
  /// one of them. Said once per path, the warning stays readable.
  final Set<String> _reportedSourceFailures = {};

  /// Compiled JS modules keyed by URL path.
  final Map<String, Uint8List> _modules = {};

  /// Source maps keyed by URL path (e.g. `foo.lib.js.map`).
  final Map<String, Uint8List> _sourcemaps = {};

  /// Module metadata keyed by URL path (e.g. `foo.lib.js.metadata`).
  final Map<String, Uint8List> _metadata = {};

  /// In-memory file storage for first-upload bootstrap files.
  /// These override build-output files and generated scripts.
  final Map<String, Uint8List> _files = {};

  /// Reloaded module descriptors for `reloaded_sources.json`.
  /// Each entry has `src`, `module`, and optionally `libraries`.
  List<Map<String, dynamic>>? _reloadedSources;

  /// Module metadata for DWDS's `MetadataProvider`, keyed by module path.
  ///
  /// A map rather than a joined string: DWDS re-reads this artifact on EVERY
  /// bootstrap request — it replaces its provider per request (dwds
  /// `strategy.dart:179-181`) and embeds the module list it derives into the
  /// served body (`_ddcLoaderSetup`, `ddc_library_bundle.dart:189-224`). The
  /// DDC loader then loads exactly that list and nothing else.
  ///
  /// So this is not bookkeeping; it is what a fresh page boots from. Held
  /// whole, it survives an incremental compile the way [_modules] and
  /// [_metadata] beside it already do. Replaced wholesale, one hot reload
  /// leaves it describing a single module, and the next page load boots
  /// nothing but that one.
  final Map<String, String> _metadataByModule = {};

  /// Module digests: module name → hash.
  Map<String, String> _moduleDigests = {};

  /// Whether the first compile has completed. Used to skip populating
  /// reloaded_sources.json on initial compile (matching Flutter).
  bool _initialCompileDone = false;

  /// Whether a compile has landed, so this server has a program to hand out.
  ///
  /// False between startup and the first successful compile — a window that
  /// only exists because a failed *first* compile does not end the run (see
  /// `web_pipeline_assembler.dart`). Upstream `flutter run` has no such
  /// window: a failed first compile returns before Chrome is launched
  /// (`resident_web_runner.dart:334-339`, launch at :367), so no browser ever
  /// reaches its server in this state. We launch Chrome anyway, which is what
  /// makes the window reachable and why [_serveBootChain] exists.
  ///
  /// This is a fact about the *server*, and the only thing that should be
  /// asked of it. What the page holds is a different fact, and the two must not
  /// be conflated: "a compile finished" is not "the page got something".
  bool get holdsProgram => _initialCompileDone;

  /// Cached DDC bootstrap scripts (generated once, served on every request).
  String? _ddcBootstrapJs;
  String? _ddcMainModuleJs;

  HttpServer? _server;

  /// DWDS instance for VM service protocol bridge.
  Dwds? _dwds;

  WebModuleServer({
    required this.webToolchain,
    required this.buildOutputDir,
    required this.entrypointFilename,
    required this.flutterBootstrapJsPath,
    required this.dartExecutable,
    required this.options,
    this.workspaceRoot,
    this.packageConfigPath,
    this.nativeNullAssertions = true,
  });

  /// The base URL of the running server.
  Uri? get uri => _server == null ? null : options.baseUri(_server!.port);

  /// Stream of connected apps from DWDS.
  Stream<AppConnection>? get connectedApps => _dwds?.connectedApps;

  /// Get a debug connection for an app (provides VM service).
  Future<DebugConnection> debugConnection(AppConnection app) =>
      _dwds!.debugConnection(app);

  /// Write a string to the in-memory file store.
  void writeFile(String path, String content) {
    _files[path] = Uint8List.fromList(utf8.encode(content));
  }

  // ---- AssetReader implementation ----

  @override
  String get basePath => '';

  @override
  Future<String?> dartSourceContents(String serverPath) async {
    // Check in-memory files first.
    final bytes = _files[serverPath];
    if (bytes != null) return utf8.decode(bytes);
    // Read from workspace filesystem.
    if (workspaceRoot != null && serverPath.endsWith('.dart')) {
      final file = File(p.join(workspaceRoot!, serverPath));
      if (file.existsSync()) return file.readAsStringSync();
      // Try packages/ → package: resolution via package_config.
      if (serverPath.startsWith('packages/') && packageConfigPath != null) {
        try {
          _packageConfig ??= await pkg.loadPackageConfig(
            File(packageConfigPath!),
          );
          final packagePath = serverPath.replaceFirst('packages/', 'package:');
          final resolved = _packageConfig!.resolve(Uri.parse(packagePath));
          if (resolved != null) {
            final source = File(resolved.toFilePath());
            if (source.existsSync()) return source.readAsStringSync();
          }
        } catch (e) {
          // A source we cannot resolve is a null to DWDS and a blank pane in
          // the debugger. `null` is the honest answer for a file that is
          // simply not there — but not for a lookup that *failed*.
          if (_reportedSourceFailures.add(serverPath)) {
            _logger.warning({
              'message': 'dart_source_lookup_failed',
              'text':
                  'Warning: could not resolve the Dart source for '
                  '$serverPath through $packageConfigPath: $e. The debugger '
                  'will show no source for it.',
              'path': serverPath,
              'packageConfig': packageConfigPath,
              'error': '$e',
            });
          }
        }
      }
    }
    return null;
  }

  @override
  Future<String?> sourceMapContents(String serverPath) async {
    var path = serverPath;
    if (path.startsWith('/')) path = path.substring(1);
    // Source maps are looked up by their .js path (strip .map).
    if (path.endsWith('.map')) {
      final bytes = _sourcemaps[path];
      if (bytes != null) return utf8.decode(bytes);
    }
    return null;
  }

  @override
  Future<String?> metadataContents(String serverPath) async {
    final path = serverPath.startsWith('/')
        ? serverPath.substring(1)
        : serverPath;
    // DWDS MetadataProvider asks for `main_module.ddc_merged_metadata`.
    if (path == 'main_module.ddc_merged_metadata' &&
        _metadataByModule.isNotEmpty) {
      return _metadataByModule.values.join('\n');
    }
    // Try exact path match in metadata store.
    final bytes = _metadata[path];
    if (bytes != null) return utf8.decode(bytes);
    return null;
  }

  @override
  Future<void> close() async {}

  // ---- Module management ----

  /// Parse DDC manifest and extract modules, source maps, and metadata.
  ///
  /// DDC frontend server writes incremental output to the same files,
  /// containing only changed modules. We merge into existing state so
  /// unchanged modules remain available.
  ///
  /// Throws [DevToolException] when the compiler reported success and its
  /// output does not back that up: a missing artifact, a manifest that does
  /// not parse, or offsets that do not fit the file they index into. A silent
  /// `return` or a skipped module for any of those shows up only as a page
  /// that 404s its way to a blank screen (first compile) or an edit that
  /// reports as reloaded and is not on screen (later compiles).
  ///
  /// The throw is the report. On the first compile it unwinds through
  /// `run_command` to `bin/flutter_bazel.dart` and ends the run; from a reload
  /// `session.dart` catches it and renders it as the reload's diagnostics.
  ///
  /// Upstream reads all four artifacts unguarded (`memory_fs.dart:29-34`), so
  /// a missing one throws there too; where it differs is skipping a module
  /// whose offsets do not fit (`memory_fs.dart:40-48`). Skipping is what makes
  /// the failure invisible, so we report instead.
  void updateModules(String dillPath, {required bool full}) {
    final manifestFile = File('$dillPath.json');
    final sourcesFile = File('$dillPath.sources');
    final mapFile = File('$dillPath.map');
    final metadataFile = File('$dillPath.metadata');

    if (!manifestFile.existsSync()) {
      throw DevToolException(
        _missingArtifact(
          manifestFile.path,
          dillPath,
          'the manifest naming every module the page loads',
        ),
      );
    }
    if (!sourcesFile.existsSync()) {
      throw DevToolException(
        _missingArtifact(
          sourcesFile.path,
          dillPath,
          'the JavaScript that the manifest slices each module out of',
        ),
      );
    }

    final Map<String, dynamic> manifest;
    try {
      manifest =
          json.decode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
    } catch (e) {
      throw DevToolException(
        'The DDC module manifest ${manifestFile.path} is not a JSON object '
        'of module offsets: $e\n'
        'Nothing from this compile can be served.',
      );
    }
    final sourcesBytes = sourcesFile.readAsBytesSync();
    final mapBytes = mapFile.existsSync() ? mapFile.readAsBytesSync() : null;
    final metadataBytes = metadataFile.existsSync()
        ? metadataFile.readAsBytesSync()
        : null;

    // A full compile produces the whole program, so what it does not name is
    // no longer part of it — the description is rebuilt rather than added to,
    // or a module a recompile dropped lingers in the list a fresh page loads
    // and the page fetches a script the server no longer has.
    //
    // Only the description. The byte stores ([_modules], [_metadata],
    // [_sourcemaps]) keep merging: nothing can request what the description
    // does not name, so bytes left behind by a superseded compile are
    // unreachable rather than wrong, and clearing them would stake the page's
    // boot on a full compile never omitting anything.
    if (full) {
      _metadataByModule.clear();
    }

    // Merge into existing state — incremental compiles only contain changed
    // modules, and unchanged modules must remain available.
    final reloadedSources = <Map<String, dynamic>>[];
    final digests = <String, String>{if (!full) ..._moduleDigests};
    // Modules the compiler described without usable metadata. Collected and
    // reported once: with no metadata there is no library list, and
    // `$dartReloadModifiedModules` reloads modules by library — so an edit in
    // one of these reports as reloaded and does not take effect. Per-module
    // warnings would be one line per module in the app.
    final withoutMetadata = <String>[];

    for (final entry in manifest.entries) {
      var modulePath = entry.key;
      if (modulePath.startsWith('/')) {
        modulePath = modulePath.substring(1);
      }
      final rawOffsets = entry.value;
      if (rawOffsets is! Map<String, dynamic>) {
        throw DevToolException(
          'The DDC module manifest ${manifestFile.path} describes module '
          '${entry.key} with ${rawOffsets.runtimeType}, not a map of '
          'section offsets.',
        );
      }
      final offsets = rawOffsets;
      final moduleName = modulePath.replaceAll('.lib.js', '');

      // Code (JS source). Required: a manifest entry with no servable code is
      // a module request that 404s.
      _modules[modulePath] = _slice(
        sourcesBytes,
        offsets: offsets,
        section: 'code',
        module: moduleName,
        artifact: sourcesFile.path,
      );
      final reloadEntry = <String, dynamic>{
        'src': '${uri ?? ''}/$modulePath',
        'module': moduleName,
        'libraries': <String>[],
      };
      reloadedSources.add(reloadEntry);
      digests[moduleName] = _modules[modulePath]!.length.toRadixString(16);

      // Source maps. The manifest is the contract: a declared section whose
      // file is absent is inconsistent output, not an optional extra.
      if (offsets.containsKey('sourcemap')) {
        if (mapBytes == null) {
          throw DevToolException(
            _missingArtifact(
              mapFile.path,
              dillPath,
              'the source maps its manifest declares for module $moduleName',
            ),
          );
        }
        _sourcemaps['$modulePath.map'] = _slice(
          mapBytes,
          offsets: offsets,
          section: 'sourcemap',
          module: moduleName,
          artifact: mapFile.path,
        );
      }

      // Metadata (for DWDS module resolution).
      if (!offsets.containsKey('metadata')) {
        withoutMetadata.add(moduleName);
        continue;
      }
      if (metadataBytes == null) {
        throw DevToolException(
          _missingArtifact(
            metadataFile.path,
            dillPath,
            'the module metadata its manifest declares for module '
            '$moduleName',
          ),
        );
      }
      final metaSlice = _slice(
        metadataBytes,
        offsets: offsets,
        section: 'metadata',
        module: moduleName,
        artifact: metadataFile.path,
      );
      _metadata['$modulePath.metadata'] = metaSlice;
      final metaStr = utf8.decode(metaSlice);
      if (metaStr.isEmpty) {
        withoutMetadata.add(moduleName);
        continue;
      }
      _metadataByModule[modulePath] = metaStr;

      // Extract libraries from metadata for reloaded_sources.
      final Map<String, dynamic> metaJson;
      try {
        metaJson = json.decode(metaStr) as Map<String, dynamic>;
      } catch (e) {
        // Not survivable, and not only ours to survive: these same bytes go
        // into the merged metadata DWDS parses line by line, where a bad line
        // rethrows out of `MetadataProvider._processMetadata` with no module
        // named. Reported here it names one.
        throw DevToolException(
          _badMetadata(
            moduleName,
            metadataFile.path,
            'is not a JSON object: $e',
          ),
        );
      }
      // Use metadata name for module field when available.
      final metaName = metaJson['name'];
      if (metaName != null) {
        if (metaName is! String) {
          throw DevToolException(
            _badMetadata(
              moduleName,
              metadataFile.path,
              'names the module with ${json.encode(metaName)}, not a string',
            ),
          );
        }
        reloadEntry['module'] = metaName;
      }
      final libs = metaJson['libraries'];
      if (libs != null) {
        if (libs is! List) {
          throw DevToolException(
            _badMetadata(
              moduleName,
              metadataFile.path,
              'lists its libraries as ${json.encode(libs)}, not an array',
            ),
          );
        }
        final libraryUris = <String>[];
        for (final lib in libs) {
          if (lib is! Map) {
            throw DevToolException(
              _badMetadata(
                moduleName,
                metadataFile.path,
                'describes a library with ${json.encode(lib)}, not an object',
              ),
            );
          }
          final importUri = lib['importUri'];
          if (importUri != null && importUri is! String) {
            throw DevToolException(
              _badMetadata(
                moduleName,
                metadataFile.path,
                'gives a library the import URI ${json.encode(importUri)}, '
                'not a string',
              ),
            );
          }
          if (importUri != null) libraryUris.add(importUri as String);
        }
        reloadEntry['libraries'] = libraryUris;
      }
    }

    if (withoutMetadata.isNotEmpty) {
      _logger.warning({
        'message': 'ddc_modules_without_metadata',
        'text':
            'Warning: the DDC compiler returned ${withoutMetadata.length} '
            'module(s) with no metadata (${withoutMetadata.join(', ')}). Hot '
            'reload identifies modules by the libraries in their metadata, so '
            'edits to those libraries will report as reloaded and will not '
            'take effect.',
        'modules': withoutMetadata,
        'dill': dillPath,
      });
    }

    // Only populate reloaded_sources.json after the first compile.
    // On initial load, it must be empty — DWDS's hot reload fetches it
    // and tries to reload every listed module. Matching Flutter's behavior.
    if (_initialCompileDone) {
      if (reloadedSources.isEmpty) {
        throw DevToolException(
          'The DDC compiler recompiled nothing for $dillPath: its manifest '
          '${manifestFile.path} names no modules.\n'
          'A recompile only happens here once something is known to have '
          'changed, so an empty result means the invalidated libraries never '
          'reached the compiler. `reloaded_sources.json` would list no '
          'modules, `\$dartReloadModifiedModules` would reload none, and the '
          'reload would report success while the page kept running the code '
          'it already had.',
        );
      }
      _reloadedSources = reloadedSources;
    } else {
      if (_modules.isEmpty) {
        throw DevToolException(
          'The first DDC compile of $dillPath produced no modules: its '
          'manifest ${manifestFile.path} is empty.\n'
          'The page loads its entrypoint and every module behind it from '
          'this server, so it would 404 its way to a blank screen.',
        );
      }
      _initialCompileDone = true;
    }
    _moduleDigests = digests;
  }

  /// The message for module metadata that is not the shape DDC emits.
  ///
  /// Every field here is read to build the module's `reloaded_sources.json`
  /// entry, which is how `$dartReloadModifiedModules` finds the libraries to
  /// reload. A bare `as` cast would report the same fault as a `TypeError`
  /// naming neither the module nor the file it came out of.
  static String _badMetadata(String module, String artifact, String fault) =>
      'The DDC metadata for module $module in $artifact $fault.\n'
      'DWDS reads the same bytes to map modules to libraries, so the debugger '
      'and hot reload cannot work from this compile.';

  /// The message for an artifact a successful compile said it wrote and did
  /// not. [role] says what the run loses with it, in the compiler's terms —
  /// "compile failed" would send the reader to their own source, and their
  /// source is not what is wrong.
  static String _missingArtifact(String path, String dillPath, String role) =>
      'The DDC compiler reported a successful compile of $dillPath but did '
      'not write $path — $role.\n'
      'Nothing from this compile can be served.';

  /// The bytes the manifest assigns to [section] of [module], checked against
  /// the artifact they index into.
  ///
  /// Every failure here means the compiler's manifest and its output disagree:
  /// a truncated artifact, or one left over from a different compile.
  static Uint8List _slice(
    Uint8List bytes, {
    required Map<String, dynamic> offsets,
    required String section,
    required String module,
    required String artifact,
  }) {
    final range = offsets[section];
    if (range is! List ||
        range.length != 2 ||
        range[0] is! int ||
        range[1] is! int) {
      throw DevToolException(
        'The DDC module manifest gives the $section of module $module as '
        '${json.encode(range)}, not a [start, end] byte range into '
        '$artifact.',
      );
    }
    final start = range[0] as int;
    final end = range[1] as int;
    if (start < 0 || end < start || end > bytes.length) {
      throw DevToolException(
        'The DDC module manifest puts the $section of module $module at '
        'bytes $start-$end of $artifact, which is ${bytes.length} bytes '
        'long. That artifact is truncated or is not the one this manifest '
        'describes.',
      );
    }
    return Uint8List.sublistView(bytes, start, end);
  }

  // ---- DWDS initialization ----

  /// Initialize DWDS for VM service protocol support.
  ///
  /// Must be called before [start] or after [start] with [chromeConnection]
  /// callback that will lazily connect to Chrome when DWDS needs it.
  ///
  /// Throws [DevToolException] when [packageConfigPath] is absent or cannot be
  /// read. DWDS resolves every `package:` URI through that config, so without
  /// it there is no VM service, no hot reload, no DevTools and no app console —
  /// the run is broken, not degraded. Returning with DWDS disabled instead
  /// produces a Chrome window that renders, reports `app.started`, and cannot
  /// be debugged or reloaded at all. `flutter run` has no code path that
  /// continues a debug web run with DWDS off either.
  /// [expressionCompiler] is what makes the debugger able to evaluate a Dart
  /// expression against the running app. Null is a real answer — DWDS then
  /// refuses each evaluation with its own message — and is what
  /// `--no-web-enable-expression-evaluation` asks for.
  Future<void> initDwds({
    required ConnectionProvider chromeConnection,
    Uri? serverUri,
    ExpressionCompiler? expressionCompiler,
  }) async {
    // Build the package URI mapper for DWDS module resolution.
    final configPath = packageConfigPath;
    if (configPath == null) {
      throw DevToolException(
        'Cannot start the web debugger: this run resolved no '
        'package_config.json, so DWDS has no way to map package: URIs to '
        'sources. Hot reload, DevTools and the app console all depend on '
        'it.',
      );
    }
    final PackageUriMapper mapper;
    try {
      mapper = PackageUriMapper(await pkg.loadPackageConfig(File(configPath)));
    } catch (e) {
      throw DevToolException(
        'Cannot start the web debugger: could not load the package config '
        'at $configPath: $e\n'
        'DWDS resolves every package: URI through it, so hot reload, '
        'DevTools and the app console would all be unavailable.',
      );
    }

    final strategyProvider = FrontendServerDdcLibraryBundleStrategyProvider(
      ReloadConfiguration.none,
      this, // AssetReader
      mapper,
      () async => _moduleDigests,
      BuildSettings(
        appEntrypoint: Uri.parse('org-dartlang-app:/$entrypointFilename'),
        canaryFeatures: true,
      ),
      packageConfigPath: packageConfigPath,
      reloadedSourcesUri: serverUri != null
          ? serverUri.replace(path: '/reloaded_sources.json')
          : Uri.parse('/reloaded_sources.json'),
    );

    _dwds = await Dwds.start(
      assetReader: this,
      buildResults: const Stream.empty(),
      chromeConnection: chromeConnection,
      toolConfiguration: ToolConfiguration(
        loadStrategy: strategyProvider.strategy,
        debugSettings: DebugSettings(
          expressionCompiler: expressionCompiler,
          // Off, unlike `flutter run`. The flag starts a second HTTP server
          // whose only client is the Dart Debug Extension — a browser
          // extension a user installs to debug a page some *other* tool
          // opened. This tool launches its own Chrome with a debugging port
          // and hands DWDS the connection, so nothing ever dials it.
          //
          // Leaving it on keeps `daemon.shutdown` from ending a web run:
          // `Dwds.stop()` closes its DevTools server, its dev handler and its
          // asset reader, but never the extension backend
          // (dart_web_debug_service.dart:52-56 — the backend is constructed in
          // `start` and handed to `DevHandler`, whose own `close` does not
          // touch it either). The listening socket outlives the teardown, and a
          // listening socket keeps the Dart VM alive, so the run answers
          // `{"message":"shutdown"}`, emits `app.stop`, and then sits there
          // until something kills it. `flutter run` gets away with the same
          // leak because flutter_tools ends every command with `exit()`.
          enableDebugExtension: false,
          // DWDS owns the Dart Development Service, the same arrangement
          // flutter_tools uses. Naming the Dart binary is what makes that
          // possible here: left to its own devices the launcher probes
          // `Platform.executable`, which under Bazel is this AOT binary, and
          // re-execs it as `<binary> development-service --vm-service-uri=…`.
          //
          // Owning it ourselves instead would cost more than the subprocess:
          // DWDS registers `hotRestart` and `fullReload` against its DDS, so
          // with no DDS of its own those land in a local registry that
          // DevTools cannot see.
          ddsConfiguration: DartDevelopmentServiceConfiguration(
            enable: true,
            serveDevTools: true,
            dartExecutable: dartExecutable,
          ),
        ),
        // The hostname the page is served from, not a constant: with
        // `--web-hostname` the injected DWDS client dials this back, and a
        // hardcoded `localhost` is a flag honoured by the bind and silently
        // dropped by the debugger.
        appMetadata: AppMetadata(hostname: options.displayHost),
      ),
    );

    // Swap the active handler to include DWDS middleware.
    // Match Flutter's web_asset_server.dart:387-393 composition:
    // DWDS middleware wraps only our asset handler (not DWDS's own handler).
    // Cascade tries DWDS handler first, then our wrapped asset handler.
    final wrappedAssetHandler = const shelf.Pipeline()
        .addMiddleware(_dwds!.middleware)
        .addHandler(_shelfHandler);
    _activeHandler = shelf.Cascade()
        .add(_dwds!.handler)
        .add(wrappedAssetHandler)
        .handler;
  }

  // ---- HTTP server ----

  /// The current request handler — swapped when DWDS is initialized.
  late shelf.Handler _activeHandler = _shelfHandler;

  /// Start the HTTP server.
  ///
  /// Call [initDwds] after this to integrate DWDS middleware —
  /// the handler is swapped in-place without restarting the server.
  ///
  /// Throws [DevToolException] when either half of the boot path is missing:
  /// the build's `flutter_bootstrap.js`, or the `flutter.js` it loads out of
  /// [buildOutputDir]. Every page this server serves boots through both, so
  /// without either the browser opens on a blank page. Checked here, before a
  /// browser is launched, the run ends naming the file instead.
  Future<Uri> start() async {
    if (!File(flutterBootstrapJsPath).existsSync()) {
      throw DevToolException(
        _noBootstrap('$flutterBootstrapJsPath does not exist'),
      );
    }
    if (!File(_flutterJsPath).existsSync()) {
      throw DevToolException(_noFlutterJs('$_flutterJsPath does not exist'));
    }

    // Use an indirection so we can swap the handler after DWDS init.
    _server = await bindWebServer(
      options,
      (request) => _activeHandler(request),
    );
    return uri!;
  }

  /// Stop the HTTP server and DWDS.
  Future<void> stop() async {
    await _dwds?.stop();
    _dwds = null;
    await _server?.close();
    _server = null;
  }

  /// Where `flutter.js` lives in the build output.
  String get _flutterJsPath => p.join(buildOutputDir, 'flutter.js');

  /// The bootstrap the build substituted for this dev loop.
  ///
  /// Read per request, and by name rather than through the static handler: a
  /// 404 for this path renders as a blank page and would say so nowhere, while
  /// a named failure reaches both the log and the 500 body. [start] has already
  /// established that the file exists, so this fails only if it goes away
  /// mid-run — a rebuild replacing the output tree, say.
  String _readBootstrap() {
    try {
      return File(flutterBootstrapJsPath).readAsStringSync();
    } on FileSystemException catch (e) {
      throw DevToolException(
        _noBootstrap(
          '$flutterBootstrapJsPath could not be read: ${e.osError ?? e}',
        ),
      );
    }
  }

  /// Why a run with no readable bootstrap cannot show anything.
  static String _noBootstrap(String cause) =>
      'Cannot serve flutter_bootstrap.js: $cause.\n'
      'The build substitutes that file from the target\'s bootstrap template; '
      'it is the whole boot path, so the page would load and stay blank.';

  /// Why a run with no `flutter.js` cannot show anything.
  static String _noFlutterJs(String cause) =>
      'Cannot serve flutter.js: $cause.\n'
      'flutter_bootstrap.js loads flutter.js to boot the engine, so the page '
      'would load and stay blank.';

  /// The generated scripts that carry a page from `flutter.js` to a running
  /// program.
  ///
  /// Held as one set, and answered ahead of every other arm of the request
  /// cascade, because whether they may be served *at all* is a single
  /// decision. The cascade's last arm serves whatever it finds in
  /// [buildOutputDir], and `main.dart.js` is a real name in a release bundle
  /// — so a gate that declined to answer rather than returning would hand the
  /// browser a compiled page that renders correctly with no dev loop behind
  /// it, which is a worse failure than the one being fixed.
  static const _bootChain = {
    'main.dart.js',
    'main_module.bootstrap.js',
    'on_load_end_bootstrap.js',
  };

  /// The boot chain's answer, or null when [path] is not part of it.
  ///
  /// Refused until [holdsProgram]. DWDS injects its client into
  /// `main_module.bootstrap.js`, at the marker the generated body opens with
  /// (dwds `handlers/injector.dart`) — so serving the boot chain before any
  /// compile is precisely what lets a debugger client attach to a page that
  /// has no program. That is the state where `hotRestart` answers "Successful
  /// hot restart" having done nothing, and a hot reload injects a delta into a
  /// blank page and reports it applied.
  /// Withholding the scripts makes the state unreachable instead of leaving
  /// it to be detected afterwards.
  ///
  /// `no-store` on both answers, because `--web-port` pins the origin across
  /// runs: either a stale refusal or a stale program could otherwise outlive
  /// the state that produced it.
  shelf.Response? _serveBootChain(String path) {
    if (!_bootChain.contains(path)) {
      return null;
    }
    const noStore = 'no-store';
    if (!holdsProgram) {
      return shelf.Response(
        HttpStatus.serviceUnavailable,
        body:
            'The dev server holds no program yet, so it will not serve '
            '$path.\n'
            'The page boots through this script, so serving it now would '
            'attach a debugger to a page with nothing to run. This clears '
            'as soon as a compile lands. If it does not, the first compile '
            'is failing and its errors are on the tool\'s output.',
        headers: {'content-type': 'text/plain', 'cache-control': noStore},
      );
    }
    final headers = {
      'content-type': contentTypeFor(path),
      'cache-control': noStore,
    };
    switch (path) {
      case 'main.dart.js':
        // Cached: the inputs never change within a run.
        _ddcBootstrapJs ??= generateDDCBootstrapScript(
          entrypoint: entrypointFilename,
        );
        return shelf.Response.ok(_ddcBootstrapJs, headers: headers);
      case 'main_module.bootstrap.js':
        _ddcMainModuleJs ??= generateDDCMainModuleScript(
          entrypoint: entrypointFilename,
          nativeNullAssertions: nativeNullAssertions,
        );
        return shelf.Response.ok(_ddcMainModuleJs, headers: headers);
      default:
        return shelf.Response.ok(generateOnLoadEndScript(), headers: headers);
    }
  }

  /// Shelf handler for all asset requests.
  Future<shelf.Response> _shelfHandler(shelf.Request request) async {
    final path = request.url.path.isEmpty ? 'index.html' : request.url.path;

    try {
      // 0. The boot chain, before anything else can answer for it.
      final bootChain = _serveBootChain(path);
      if (bootChain != null) {
        return bootChain;
      }

      // 1. In-memory files (first-upload bootstrap files override everything).
      if (_files.containsKey(path)) {
        return shelf.Response.ok(
          _files[path]!,
          headers: {'content-type': contentTypeFor(path)},
        );
      }

      // 2. flutter_bootstrap.js — the build's, substituted for the dev loop.
      if (path == 'flutter_bootstrap.js') {
        return shelf.Response.ok(
          _readBootstrap(),
          headers: {'content-type': contentTypeFor(path)},
        );
      }

      // 3. DDC modules from memory.
      if (_modules.containsKey(path)) {
        return shelf.Response.ok(
          _modules[path]!,
          headers: {'content-type': contentTypeFor(path)},
        );
      }

      // Source maps from memory.
      if (_sourcemaps.containsKey(path)) {
        return shelf.Response.ok(
          _sourcemaps[path]!,
          headers: {'content-type': contentTypeFor(path)},
        );
      }

      // 4. reloaded_sources.json for hot reload/restart.
      if (path == 'reloaded_sources.json') {
        return shelf.Response.ok(
          json.encode(_reloadedSources ?? []),
          headers: {'content-type': contentTypeFor(path)},
        );
      }

      // 6. dart_sdk.js from DDC build outputs.
      if (path == 'dart_sdk.js') {
        return _serveFile(webToolchain.dartSdkJs);
      }
      if (path == 'dart_sdk.js.map') {
        final mapPath = '${webToolchain.dartSdkJs}.map';
        if (File(mapPath).existsSync()) {
          return _serveFile(mapPath);
        }
      }

      // 7. DDC module loader + stack trace mapper from DDC build outputs.
      if (path == 'ddc_module_loader.js') {
        return _serveFile(webToolchain.ddcModuleLoaderJs);
      }
      if (path == 'stack_trace_mapper.js') {
        return _serveFile(webToolchain.stackTraceMapperJs);
      }

      // 8. Metadata files for DWDS.
      if (_metadata.containsKey(path)) {
        return shelf.Response.ok(
          _metadata[path]!,
          headers: {'content-type': contentTypeFor(path)},
        );
      }

      // 9. Static files from build output directory. The path came off the
      // wire, so it is served contained within the bundle.
      return serveFileWithin(buildOutputDir, path);
    } catch (e, stack) {
      // The 500 stays: one request failing is not grounds to end a run, and
      // upstream serves on through the same failure (`web_asset_server.dart:
      // 400-406` logs and keeps serving). What it is grounds for is saying so
      // — the browser is the only party that knows, and it reports a failed
      // asset as a blank page.
      _logger.severe(
        {
          'message': 'asset_request_failed',
          'text': 'Error serving /$path: $e',
          'path': path,
          'error': '$e',
        },
        e,
        stack,
      );
      return shelf.Response.internalServerError(body: 'Error: $e');
    }
  }
}
