"""Unit tests for web application helpers."""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts", "unittest")
load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("//flutter/private:flutter_web_application.bzl", "flutter_web_bundle")
load("//flutter/private:validation.bzl", "escape_html", "is_valid_web_compiler_renderer")
load(
    "//flutter/private:web_service_worker.bzl",
    "SERVICE_WORKER_JS",
    "SERVICE_WORKER_VERSION",
    "service_worker_load_args",
    "service_worker_version_for",
)
load(":action_content.bzl", "written_json")

def _html_title_escaping_test_impl(ctx):
    """Test that HTML special characters in titles are properly escaped."""
    env = unittest.begin(ctx)

    test_cases = [
        ("My App", "My App"),
        ("App & Co", "App &amp; Co"),
        ("<script>", "&lt;script&gt;"),
        ('He said "hi"', "He said &quot;hi&quot;"),
        ("Normal Title", "Normal Title"),
    ]

    for title, expected in test_cases:
        asserts.equals(env, expected, escape_html(title), "Escaping '%s'" % title)

    return unittest.end(env)

def _web_compiler_renderer_validation_test_impl(ctx):
    """Test that invalid compiler+renderer combos are rejected."""
    env = unittest.begin(ctx)

    # Valid combinations.
    asserts.true(env, is_valid_web_compiler_renderer("dart2wasm", "skwasm"), "dart2wasm+skwasm should be valid")
    asserts.true(env, is_valid_web_compiler_renderer("dart2wasm", "canvaskit"), "dart2wasm+canvaskit should be valid")
    asserts.true(env, is_valid_web_compiler_renderer("dart2js", "canvaskit"), "dart2js+canvaskit should be valid")

    # Invalid: dart2js cannot use skwasm (skwasm requires wasm).
    asserts.false(env, is_valid_web_compiler_renderer("dart2js", "skwasm"), "dart2js+skwasm should be invalid")

    return unittest.end(env)

def _service_worker_tears_down_test_impl(ctx):
    """The shipped worker must remove itself, and must not cache."""
    env = unittest.begin(ctx)

    asserts.true(
        env,
        "self.registration.unregister()" in SERVICE_WORKER_JS,
        "The worker must unregister itself — tearing down a previously " +
        "installed caching worker is the only reason it ships.",
    )
    asserts.true(
        env,
        "self.skipWaiting()" in SERVICE_WORKER_JS,
        "Without skipWaiting the teardown waits for every tab to close.",
    )
    asserts.true(
        env,
        "client.navigate(client.url)" in SERVICE_WORKER_JS,
        "Controlled clients must be reloaded, or they keep reading the " +
        "old worker's cache for the rest of the session.",
    )

    # A cache-first worker whose script never changes pins a visitor to the
    # build they first loaded, with no way to push a fix. Nothing that touches
    # the Cache API belongs in a worker generated by these rules.
    for banned in ["caches.open", "caches.match", "cache.addAll", "CACHE_NAME"]:
        asserts.false(
            env,
            banned in SERVICE_WORKER_JS,
            "The generated worker must not cache (found `%s`)." % banned,
        )

    return unittest.end(env)

def _service_worker_load_args_test_impl(ctx):
    """`_flutter.loader.load` gets the version, and only the version."""
    env = unittest.begin(ctx)

    args = service_worker_load_args(pwa = True)
    asserts.true(
        env,
        "serviceWorkerSettings" in args,
        "The loader needs serviceWorkerSettings to register at all.",
    )

    # The version arrives through the templating pass, as the same
    # `{{flutter_service_worker_version}}` built-in a user-supplied bootstrap
    # would reference — so the default template exercises the path a copied
    # upstream bootstrap takes, instead of a private shortcut around it.
    asserts.true(
        env,
        "{{flutter_service_worker_version}}" in args,
        "The version must reach the bootstrap through the built-in, got %r" % args,
    )

    # flutter.js registers unconditionally when handed a serviceWorkerUrl,
    # which would install a worker for first-time visitors who have nothing to
    # tear down, and logs a deprecation warning to their console besides.
    asserts.false(
        env,
        "serviceWorkerUrl" in args,
        "serviceWorkerUrl defeats the existing-registration gate.",
    )

    asserts.equals(
        env,
        "",
        service_worker_load_args(pwa = False),
        "pwa = False must produce a bare `load()` with no worker settings.",
    )

    return unittest.end(env)

def _service_worker_version_test_impl(ctx):
    """The version has to survive flutter.js's `endsWith` comparison."""
    env = unittest.begin(ctx)

    # flutter.js decides whether the active worker is current with
    # `registration.active.scriptURL.endsWith(version)`. A version containing
    # URL-significant characters would be mangled between the two sides.
    for banned in ["?", "&", "=", "/", " ", "#"]:
        asserts.false(
            env,
            banned in SERVICE_WORKER_VERSION,
            "Version must be a suffix-safe literal (found `%s`)." % banned,
        )
    asserts.true(
        env,
        len(SERVICE_WORKER_VERSION) > 0,
        "An empty version makes every scriptURL compare equal.",
    )

    # The version is derived from the worker source rather than written down,
    # so that editing the worker cannot leave a stale version behind. Asserting
    # it *moves* is the whole point: a derivation that ignored its input would
    # satisfy every other check in this test.
    asserts.equals(
        env,
        SERVICE_WORKER_VERSION,
        service_worker_version_for(SERVICE_WORKER_JS),
        "The shipped version must be the one derived from the shipped worker.",
    )
    asserts.false(
        env,
        SERVICE_WORKER_VERSION == service_worker_version_for(
            SERVICE_WORKER_JS + "\n// a change to the worker\n",
        ),
        "A changed worker must produce a changed version.",
    )

    # The fixed prefix is what keeps two versions from comparing equal under
    # `endsWith`: without it, "123" is a suffix of "4123" and flutter.js would
    # read a stale worker as current.
    asserts.true(
        env,
        SERVICE_WORKER_VERSION.startswith("rules_flutter_"),
        "Version must carry the fixed prefix, got %r" % SERVICE_WORKER_VERSION,
    )

    return unittest.end(env)

_t0_test = unittest.make(_html_title_escaping_test_impl)
_t1_test = unittest.make(_web_compiler_renderer_validation_test_impl)
_t2_test = unittest.make(_service_worker_tears_down_test_impl)
_t3_test = unittest.make(_service_worker_load_args_test_impl)
_t4_test = unittest.make(_service_worker_version_test_impl)

# -- Analysis tests over the flutter_web_bundle rule -------------------------
#
# These read the actual dart2wasm/dart2js command lines and declared outputs
# of fixture targets, in a pinned compilation mode, so that the defines a web
# build carries per mode — and the `-c dbg` dev-loop contract (dev config +
# DDC side-files) — are asserted where they live rather than inferred.

def _action(env, mnemonic):
    """The single action with `mnemonic` on the target under test."""
    found = [a for a in analysistest.target_actions(env) if a.mnemonic == mnemonic]
    asserts.equals(env, 1, len(found), "expected exactly one %s action" % mnemonic)
    return found[0] if found else None

def _assert_argv(env, action, present = [], absent_substrings = []):
    """Assert exact args present and substrings absent on an action's argv."""
    if action == None:
        return
    argv = action.argv
    for arg in present:
        asserts.true(env, arg in argv, "%r missing from %s argv: %s" % (arg, action.mnemonic, argv))
    for sub in absent_substrings:
        matches = [a for a in argv if sub in a]
        asserts.equals(env, [], matches, "%r must not appear in %s argv" % (sub, action.mnemonic))

def _assert_optimization_level(env, action, expected):
    """Assert the action states exactly one `-O`, and that it is `expected`.

    Asserted as "exactly one" rather than "contains": both compilers default
    to `-O1` when the flag is absent, so a level that fails to reach the
    command line is not a neutral outcome, and a second `-O` would silently
    win over the first.

    Args:
        env: The analysistest env.
        action: The action to read, from `_action`.
        expected: The level as an int.
    """
    if action == None:
        return
    levels = [a for a in action.argv if a.startswith("-O")]
    asserts.equals(
        env,
        ["-O%d" % expected],
        levels,
        "%s must state exactly one optimization level" % action.mnemonic,
    )

def _default_basenames(env):
    target = analysistest.target_under_test(env)
    return [f.basename for f in target[DefaultInfo].files.to_list()]

def _dbg_web_defines_test_impl(ctx):
    """A `-c dbg` web build is a debug build: no product define, asserts on.

    Both compilers are checked — the dart2js fallback ships in the same
    bundle, and a fallback silently compiled as release would be the same bug
    reappearing on WASM-less browsers.
    """
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2Wasm"),
        present = [
            "--extra-compiler-option=--enable-asserts",
            "--no-minify",
            # Debug shipped stripped until `strip_wasm` was gated on release.
            # A stripped debug WASM is a stack trace with no names in it.
            "--no-strip-wasm",
        ],
        # `toString()` bodies have to survive a debug build: dropping them is
        # what makes `'$widget'` stop naming the type, and debug is where that
        # output is read.
        absent_substrings = ["dart.vm.product", "dart.vm.profile", "delete-tostring"],
    )
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        present = ["--enable-asserts", "--no-minify", "--native-null-assertions"],
        absent_substrings = ["dart.vm.product", "dart.vm.profile", "frequency-based"],
    )

    # Upstream's debug levels, which the two compilers disagree about: dart2js
    # stops at 1 because level 0 "is not well supported" there, while dart2wasm
    # takes 0 — it compiles a debug app in half the time for twice the output,
    # which is the trade a debug build exists to make. Both were 2 until this
    # was corrected, which is what minified debug JS before `--no-minify` was
    # stated outright.
    _assert_optimization_level(env, _action(env, "FlutterDart2Wasm"), 0)
    _assert_optimization_level(env, _action(env, "FlutterDart2JS"), 1)

    # The dbg dev-loop contract: the target's outputs still carry the dev
    # config and the DDC side-files the dev tool's DWDS loop stages.
    basenames = _default_basenames(env)
    for expected in [
        "_web_fixture_dev_config.json",
        "_web_fixture.dev_package_config.json",
        "_web_fixture_ddc_outline.dill",
        "_web_fixture_ddc_libraries.json",
        "_web_fixture_ddc_dart_sdk.js",
        "_web_fixture_ddc_module_loader.js",
        "_web_fixture_ddc_stack_trace_mapper.js",
        "_web_fixture.agent_extensions.dart",
        "_web_fixture_dev_flutter_bootstrap.js",
    ]:
        asserts.true(env, expected in basenames, "%s missing from dbg outputs: %s" % (expected, basenames))

    # The dev server answers `/flutter_bootstrap.js` with the file this names.
    # Named rather than found by suffix, so a run cannot pick up a sibling
    # target's bootstrap and boot the wrong app.
    dev_config = written_json(env, "_dev_config.json")
    if dev_config != None:
        asserts.true(
            env,
            dev_config["flutterBootstrapJs"].endswith("_web_fixture_dev_flutter_bootstrap.js"),
            "the dev config must name the dev loop's bootstrap: %s" % dev_config.get("flutterBootstrapJs"),
        )

    # The dev loop serves this bundle's index.html next to a bootstrap of its
    # own, so a debug build is where inlining the boot path has to be refused.
    _assert_template_wiring(env, expect_dev_loop_guard = True)
    return analysistest.end(env)

_dbg_web_defines_test = analysistest.make(
    _dbg_web_defines_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
)

def _profile_web_defines_test_impl(ctx):
    """`profile = True` is its own mode, and neither of the other two.

    Asserted from a `-c dbg` configuration on purpose: the attr overrides the
    compilation-mode mapping, so a profile build assembled under `-c dbg` must
    still come out as profile. An implementation that only special-cased
    `-c opt` would pass an opt-configured version of this test.
    """
    env = analysistest.begin(ctx)

    # dart2wasm: profile carries its own define, and the release-shaped
    # `toString()` stripping that makes it representative of release.
    _assert_argv(
        env,
        _action(env, "FlutterDart2Wasm"),
        present = [
            "-Ddart.vm.profile=true",
            # Left unminified and unstripped on purpose: a profile build
            # exists to be read, and upstream gates both on release.
            "--no-minify",
            "--no-strip-wasm",
            "--extra-compiler-option=--delete-tostring-package-uri=dart:ui",
            "--extra-compiler-option=--delete-tostring-package-uri=package:flutter",
        ],
        absent_substrings = ["enable-asserts", "dart.vm.product"],
    )

    # dart2js gets the define but not the tostring options — upstream's
    # `Dart2JSTarget` has no equivalent, and dart2js would reject them.
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        present = ["-Ddart.vm.profile=true", "--no-minify", "--native-null-assertions"],
        absent_substrings = ["enable-asserts", "dart.vm.product", "delete-tostring"],
    )

    # A profile build optimizes exactly as release does — it exists to measure
    # release, so a lower level here would measure something nobody ships.
    _assert_optimization_level(env, _action(env, "FlutterDart2Wasm"), 2)
    _assert_optimization_level(env, _action(env, "FlutterDart2JS"), 4)

    # A profile build is not a dev-loop build: nothing may serve it as one.
    for basename in _default_basenames(env):
        asserts.false(
            env,
            "dev_config" in basename or "_ddc_" in basename,
            "dev-loop file %s leaked into a profile build" % basename,
        )
    _assert_template_wiring(env, expect_dev_loop_guard = False)
    return analysistest.end(env)

_profile_web_defines_test = analysistest.make(
    _profile_web_defines_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
)

def _opt_web_defines_test_impl(ctx):
    """A `-c opt` web build is a release build: product define, no asserts."""
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2Wasm"),
        present = [
            "-Ddart.vm.product=true",
            "--minify",
            "--strip-wasm",
            # Release drops `toString()` bodies upstream. Missing here until
            # profile mode landed, which is why it is pinned in both modes
            # that carry it rather than only in the new one.
            "--extra-compiler-option=--delete-tostring-package-uri=dart:ui",
            "--extra-compiler-option=--delete-tostring-package-uri=package:flutter",
        ],
        absent_substrings = ["enable-asserts", "dart.vm.profile"],
    )
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        present = ["-Ddart.vm.product=true", "--minify", "--native-null-assertions"],
        absent_substrings = ["enable-asserts", "dart.vm.profile"],
    )

    # The release levels, and the reason they differ: dart2js goes to 4, while
    # dart2wasm stops at 2 because that is the highest level using only sound
    # optimizations and upstream's benchmarks put the rest at marginal. A
    # single shared level cannot state both, which is why there is no single
    # shared attr.
    _assert_optimization_level(env, _action(env, "FlutterDart2Wasm"), 2)
    _assert_optimization_level(env, _action(env, "FlutterDart2JS"), 4)

    # Release output is the bundle directory alone — none of the dev-loop
    # side-files may leak into it.
    for basename in _default_basenames(env):
        asserts.false(
            env,
            "dev_config" in basename or "_ddc_" in basename,
            "dev-loop file %s leaked into release outputs" % basename,
        )

    # Nothing serves a release bundle but a web server, so an index.html that
    # inlines the bootstrap is a legitimate single-request deployment here.
    _assert_template_wiring(env, expect_dev_loop_guard = False)
    return analysistest.end(env)

_opt_web_defines_test = analysistest.make(
    _opt_web_defines_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "opt"},
)

def _dev_config_test_impl(ctx):
    """`_dev_config.json` is the artifact the whole DDC dev loop hangs off.

    The dev tool reads every key below by name — a run whose `_dev_config.json`
    is missing ends deliberately, quoting the file (`web_e2e_test.dart`), so a
    file that is *present but wrong* is the failure with no guard at all. The
    dbg-outputs test above only proves it was written; this proves what is in it.

    `expect_entrypoint` is passed in rather than derived, because deriving it
    here would just re-run the rule's own `main.short_path` arithmetic and
    agree with itself.
    """
    env = analysistest.begin(ctx)
    config = written_json(env, "_dev_config.json")
    if config == None:
        return analysistest.end(env)

    # The synthetic entrypoint the dev tool compiles. Getting this wrong is a
    # frontend server that compiles the wrong library and an app that never
    # starts, so both branches of the rule's `<pkg>/lib/` strip are pinned —
    # see the two fixtures in `_setup_web_fixtures`.
    asserts.equals(env, ctx.attr.expect_entrypoint, config["appEntrypoint"])

    # Staged beside the synthetic entrypoint and imported by it. Named by the
    # build precisely so the dev tool never has to search for it.
    asserts.true(
        env,
        config["agentExtensions"].endswith(".agent_extensions.dart"),
        "agentExtensions must name the staged file, got %r" % config["agentExtensions"],
    )

    # Replayed as -D on the resident frontend server, so a reload recompiles
    # under the same environment the initial build used.
    asserts.equals(env, ["from.attr=1"], config["dartDefines"])

    # The dev loop asserts native nullability through its own bootstrap rather
    # than a compiler flag, so the value has to travel to it explicitly or a
    # `native_null_assertions = False` app would keep checking under
    # `flutter_bazel run` while its bundle had stopped.
    asserts.equals(env, True, config["nativeNullAssertions"])

    # A fixture with no web plugins. The empty state must be expressible and
    # asserted: the dev tool distinguishes "this app has no registrant" from
    # "the registrant went missing", and a sentinel here would collapse the two.
    asserts.equals(env, "", config["webPluginRegistrant"])

    # Always written in dbg — the dev package config is what lets a
    # source-assembled app resolve `package:` URIs across the live tree rather
    # than the frozen assembled copy, and every dbg web run is a dev-loop run.
    asserts.true(
        env,
        config["devPackageConfig"].endswith(".dev_package_config.json"),
        "devPackageConfig must name the dbg dev package config, got %r" %
        config["devPackageConfig"],
    )

    # Codegen keys in their non-codegen state. A plain app must contribute no
    # filesystem roots and no generated sources; phantom entries here would put
    # the frontend server on a multi-root layout it has no sources for.
    asserts.equals(env, [], config["filesystemRoots"])
    asserts.equals(env, [], config["generatedSourcePaths"])
    asserts.equals(env, [], config["generatedSourceUris"])

    # The scheme the dev tool hands its frontend server as
    # `--filesystem-scheme`; the URIs it then invalidates are built on it, so
    # the two sides have to name the same one.
    asserts.equals(env, "org-dartlang-app", config["filesystemScheme"])

    # The app itself, which is how the dev tool maps a live edit of a file
    # back to the `package:` URI to invalidate. The fixture declares no `srcs`,
    # so its `main` is the only first-party source here — and it is listed
    # under this target's own package, not the workspace root.
    #
    # An app record claiming `lib_root = ""` would match no file of a package
    # that does not sit at the workspace root, so a live edit to such an app's
    # `main` would map to no package at all.
    asserts.equals(
        env,
        [{"name": "web_fixture", "libRoot": "flutter/tests"}],
        config["sourcePackages"],
    )

    # The tools the dev tool spawns or reads by path. None may be empty: an
    # empty path here surfaces as a spawn failure deep in the dev loop, far
    # from the build that wrote it.
    for key in [
        "engineRevision",
        "flutterVersion",
        "dartSdkRoot",
        "dartaotruntime",
        "frontendServer",
        "patchedSdkRoot",
    ]:
        asserts.true(env, len(config[key]) > 0, "%s must not be empty" % key)
    return analysistest.end(env)

_dev_config_test = analysistest.make(
    _dev_config_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
    attrs = {"expect_entrypoint": attr.string(mandatory = True)},
)

def _no_package_uri_refused_test_impl(ctx):
    """A `main` outside the package's `lib/` stops a dbg build instead of guessing.

    There is no `package:` URI for such a file, and the dev loop's synthetic
    entrypoint imports the app by package URI or not at all. The rule used to
    fabricate `package:<name>/main.dart` here — a library that, resolved
    against the app's own record, was some *other* app's entrypoint. The run
    then booted that program and reported nothing, which is the failure this
    refusal replaces.
    """
    env = analysistest.begin(ctx)

    # Named by path, so the message identifies the file rather than the rule.
    asserts.expect_failure(env, "web_fixture_main.dart")

    # And the message has to say where the file belongs, or it reads as
    # "unsupported" rather than "move it".
    asserts.expect_failure(env, "flutter/tests/lib/")
    return analysistest.end(env)

_no_package_uri_refused_test = analysistest.make(
    _no_package_uri_refused_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
    expect_failure = True,
)

def _dev_config_overrides_test_impl(ctx):
    """The dev-config keys carry the target's values, not fixed ones.

    The main dev-config test reads a fixture that sets neither, so both keys
    sit at their defaults there and an implementation that hardcoded them
    would pass. This fixture sets both away from their defaults, which is the
    only way the *writing* side is pinned — the dev tool's tests cover the
    reading side and cannot see a build that never wrote the value.
    """
    env = analysistest.begin(ctx)
    config = written_json(env, "_dev_config.json")
    if config == None:
        return analysistest.end(env)
    asserts.equals(env, False, config["nativeNullAssertions"])
    asserts.equals(env, ["test-experiment"], config["enableExperiments"])
    return analysistest.end(env)

_dev_config_overrides_test = analysistest.make(
    _dev_config_overrides_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
)

def _wasm_source_map_test_impl(ctx):
    """`source_maps = True` declares main.dart.wasm.map and ships it.

    dart2wasm writes `<output>.map` and embeds a sourceMappingURL pointing at
    that basename, so the declared output and the bundled name must both be
    exactly `main.dart.wasm.map`.
    """
    env = analysistest.begin(ctx)
    wasm_action = _action(env, "FlutterDart2Wasm")
    _assert_argv(env, wasm_action, absent_substrings = ["--no-source-maps"])
    out_basenames = [f.basename for f in wasm_action.outputs.to_list()] if wasm_action else []
    asserts.true(
        env,
        "main.dart.wasm.map" in out_basenames,
        "main.dart.wasm.map not declared by dart2wasm action: %s" % out_basenames,
    )

    # The bundler must be told to place it at the bundle root under the same
    # name the compiled wasm references.
    configs = [
        a
        for a in analysistest.target_actions(env)
        if a.mnemonic == "FileWrite" and
           a.outputs.to_list()[0].basename.endswith("_web_bundle_config.json")
    ]
    asserts.equals(env, 1, len(configs), "expected exactly one bundle config write")
    if configs:
        asserts.true(
            env,
            "main.dart.wasm.map" in configs[0].content,
            "main.dart.wasm.map missing from bundle config: %s" % configs[0].content,
        )
    return analysistest.end(env)

_wasm_source_map_test = analysistest.make(_wasm_source_map_test_impl)

def _wasm_no_source_map_test_impl(ctx):
    """Without `source_maps` the compile is told so and declares no map."""
    env = analysistest.begin(ctx)
    wasm_action = _action(env, "FlutterDart2Wasm")
    _assert_argv(env, wasm_action, present = ["--no-source-maps"])
    out_basenames = [f.basename for f in wasm_action.outputs.to_list()] if wasm_action else []
    for basename in out_basenames:
        asserts.false(env, basename.endswith(".map"), "unexpected source map output %s" % basename)
    return analysistest.end(env)

_wasm_no_source_map_test = analysistest.make(_wasm_no_source_map_test_impl)

def _minify_override_test_impl(ctx):
    """An explicit `minify_*` beats the mode, in both directions at once.

    Read from `-c dbg`, where "auto" would give both compilers `--no-minify`.
    The fixture asks for the opposite of that on one compiler and the same as
    it on the other, so an implementation that ignored the attr, or that
    applied one compiler's value to both, fails here.
    """
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        present = ["--minify"],
        absent_substrings = ["--no-minify"],
    )
    _assert_argv(
        env,
        _action(env, "FlutterDart2Wasm"),
        present = ["--no-minify"],
    )
    return analysistest.end(env)

_minify_override_test = analysistest.make(
    _minify_override_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
)

def _optimization_override_test_impl(ctx):
    """An explicit `optimization_level_*` beats the mode, on one compiler only.

    Read from `-c dbg`, where "auto" would give dart2js 1 and dart2wasm 0. The
    fixture asks dart2js for 3 and leaves dart2wasm alone, so an
    implementation that ignored the attr, or that let one compiler's value
    reach both, fails here — and 3 is a level neither compiler's default ever
    produces in any mode, so it cannot be arrived at by accident.
    """
    env = analysistest.begin(ctx)
    _assert_optimization_level(env, _action(env, "FlutterDart2JS"), 3)
    _assert_optimization_level(env, _action(env, "FlutterDart2Wasm"), 0)
    return analysistest.end(env)

_optimization_override_test = analysistest.make(
    _optimization_override_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "dbg"},
)

def _optimization_zero_test_impl(ctx):
    """`"0"` reaches the command line rather than being read as "unset".

    Both compilers default to `-O1` when no `-O` is passed, so a level of 0
    that fails to appear is not a no-op — it is a build quietly running one
    level higher than it was told to. Asserted in `-c opt`, where the mode
    default for both compilers is something other than 0.
    """
    env = analysistest.begin(ctx)
    _assert_optimization_level(env, _action(env, "FlutterDart2JS"), 0)
    _assert_optimization_level(env, _action(env, "FlutterDart2Wasm"), 0)
    return analysistest.end(env)

_optimization_zero_test = analysistest.make(
    _optimization_zero_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "opt"},
)

def _js_only_settings_test_impl(ctx):
    """The dart2js settings reach the compile a `dart2js` target actually runs.

    Every other assertion here reads a `compiler = "dart2wasm"` target, whose
    dart2js action is the *fallback*. That leaves the JS-only call site — a
    separate call in the rule — pinned by nothing: dropping its settings there
    keeps every other test green while an explicit level or minify choice on a
    `compiler = "dart2js"` target silently reaches nothing, which is the class
    of bug this ruleset refuses at analysis time rather than ships.

    Read from `-c opt`, where the defaults are 4 and `--minify`, so the
    fixture's 3 and `--no-minify` cannot be arrived at by ignoring it.
    """
    env = analysistest.begin(ctx)
    _assert_optimization_level(env, _action(env, "FlutterDart2JS"), 3)
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        present = ["--no-minify"],
    )

    # There is no second compile to have taken the settings instead.
    asserts.equals(
        env,
        [],
        [a for a in analysistest.target_actions(env) if a.mnemonic == "FlutterDart2Wasm"],
        "a dart2js target must run no wasm compile",
    )
    return analysistest.end(env)

_js_only_settings_test = analysistest.make(
    _js_only_settings_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "opt"},
)

def _optimization_wasm_on_js_refused_test_impl(ctx):
    """The wasm-only refusal covers the wasm optimization level too."""
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, "optimization_level_wasm")
    asserts.expect_failure(env, "compiler = \"dart2wasm\"")
    return analysistest.end(env)

_optimization_wasm_on_js_refused_test = analysistest.make(
    _optimization_wasm_on_js_refused_test_impl,
    expect_failure = True,
)

def _js_flags_test_impl(ctx):
    """The dart2js-only flags reach dart2js, and only dart2js.

    One fixture carries them all: each is an independent `if` on the same
    command line, so separate fixtures would multiply full compile analyses
    without separating anything. The absence assertions on the WASM action are
    the load-bearing half — `dart compile wasm` rejects every one of these
    outright ("Could not find an option named"), so a flag leaking across
    would break the build rather than merely misconfigure it.
    """
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        present = ctx.attr.expect_js,
        absent_substrings = ctx.attr.expect_not_js,
    )
    _assert_argv(
        env,
        _action(env, "FlutterDart2Wasm"),
        absent_substrings = ctx.attr.expect_not_wasm,
    )
    return analysistest.end(env)

_js_flags_test = analysistest.make(
    _js_flags_test_impl,
    attrs = {
        "expect_js": attr.string_list(mandatory = True),
        "expect_not_js": attr.string_list(mandatory = True),
        "expect_not_wasm": attr.string_list(mandatory = True),
    },
)

def _experiments_test_impl(ctx):
    """An experiment reaches every step that parses the source.

    Read from `-c opt`, which is the only configuration where the icon
    tree-shake kernel compile exists at all — and that compile is the one a
    web-only implementation forgets, because both real compilers would have
    accepted the code without it.
    """
    env = analysistest.begin(ctx)
    flag = "--enable-experiment=test-experiment"
    for mnemonic in ["FlutterDart2Wasm", "FlutterDart2JS"]:
        _assert_argv(env, _action(env, mnemonic), present = [flag])

    kernels = [
        a
        for a in analysistest.target_actions(env)
        if a.mnemonic == "FlutterKernelCompile"
    ]
    asserts.equals(env, 1, len(kernels), "expected the icon tree-shake kernel compile")
    if kernels:
        _assert_argv(env, kernels[0], present = [flag])
    return analysistest.end(env)

_experiments_test = analysistest.make(
    _experiments_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "opt"},
)

def _dump_info_test_impl(ctx):
    """`dump_info` produces a named artifact, and keeps it out of the bundle.

    Three joints: the flag dart2js actually needs, the extraction the bundler
    is told to perform, and the exclusion that stops the same file being
    deployed. The last is the one worth pinning — without it the artifact
    still exists and every other assertion here passes, while every visitor
    downloads a description of the whole program.
    """
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        # NOT the bare `--dump-info`, which writes a binary `.info.data`.
        present = ["--stage=dump-info-all"],
    )

    bundle = written_json(env, "_web_bundle_config.json")
    if bundle == None:
        return analysistest.end(env)

    extracts = bundle["extracts"]
    asserts.equals(env, 1, len(extracts), "expected one extract, got %s" % extracts)
    if extracts:
        asserts.true(
            env,
            extracts[0]["src"].endswith("/main.dart.js.info.json"),
            "the extract must name dart2js's own output path, got %r" % extracts[0]["src"],
        )
        asserts.true(
            env,
            extracts[0]["dst"].endswith("_dart2js_info.json"),
            "the extract must land on the declared file, got %r" % extracts[0]["dst"],
        )

    # Asserted to exist before being asserted about: the compile output is
    # copied to the bundle root, and a loop over zero matching entries would
    # pass however the exclusion were configured.
    roots = [e for e in bundle["copy_dirs"] if e["dst"] == "."]
    asserts.equals(env, 1, len(roots), "expected one bundle-root copy_dirs entry")
    for entry in roots:
        asserts.true(
            env,
            "*.info.json" in entry.get("exclude", []),
            "the dump-info JSON must not be deployed: %s" % entry,
        )

    # And it is reachable by name rather than only as a file inside a tree.
    group = analysistest.target_under_test(env)[OutputGroupInfo].dump_info.to_list()
    asserts.equals(env, 1, len(group), "dump_info output group: %s" % group)
    return analysistest.end(env)

_dump_info_test = analysistest.make(_dump_info_test_impl)

def _no_dump_info_test_impl(ctx):
    """With the attr off, nothing is asked for and the group is empty."""
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2JS"),
        absent_substrings = ["dump-info"],
    )
    bundle = written_json(env, "_web_bundle_config.json")
    if bundle != None:
        asserts.equals(env, [], bundle["extracts"])
    asserts.equals(
        env,
        [],
        analysistest.target_under_test(env)[OutputGroupInfo].dump_info.to_list(),
    )
    return analysistest.end(env)

_no_dump_info_test = analysistest.make(_no_dump_info_test_impl)

def _no_strip_release_test_impl(ctx):
    """`strip_wasm = False` reaches the one mode that would have stripped.

    Read from `-c opt`. The debug and profile assertions elsewhere prove the
    release gate; only this proves the attr is consulted at all, rather than
    the gate alone deciding.
    """
    env = analysistest.begin(ctx)
    _assert_argv(
        env,
        _action(env, "FlutterDart2Wasm"),
        present = ["--no-strip-wasm", "-Ddart.vm.product=true"],
    )
    return analysistest.end(env)

_no_strip_release_test = analysistest.make(
    _no_strip_release_test_impl,
    config_settings = {"//command_line_option:compilation_mode": "opt"},
)

def _strip_wasm_on_js_refused_test_impl(ctx):
    """The same refusal covers the other wasm-only attr, named for itself."""
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, "strip_wasm")
    asserts.expect_failure(env, "compiler = \"dart2wasm\"")
    return analysistest.end(env)

_strip_wasm_on_js_refused_test = analysistest.make(
    _strip_wasm_on_js_refused_test_impl,
    expect_failure = True,
)

def _wasm_only_attr_refused_test_impl(ctx):
    """A wasm-only setting on a dart2js target is refused, by attr name."""
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, "minify_wasm")

    # The message has to name the way out, or it reads as "you may not have
    # this" rather than "ask the other compiler for it".
    asserts.expect_failure(env, "compiler = \"dart2wasm\"")
    return analysistest.end(env)

_wasm_only_attr_refused_test = analysistest.make(
    _wasm_only_attr_refused_test_impl,
    expect_failure = True,
)

def _template_config(env):
    """The config the templating action is driven by, decoded."""
    return written_json(env, "_web_template_config.json")

def _template_action_outputs(env):
    """Basenames the single FlutterWebTemplate action declares."""
    action = _action(env, "FlutterWebTemplate")
    if action == None:
        return []
    return [f.basename for f in action.outputs.to_list()]

def _assert_template_wiring(env, expect_dev_loop_guard):
    """The templating pass's plumbing, asserted at the three joints it has.

    What the config says, what the action declares, and where the bundler is
    told to put it. The substitution itself is the tool's own business and is
    covered by `web_template_test.dart`; asserting text here would only
    re-run the same code twice.
    """
    config = _template_config(env)
    if config == None:
        return
    files = config["files"]

    # Bootstrap first: index.html inlines the *substituted* bootstrap through
    # `{{flutter_bootstrap_js}}`, which only works if it was already produced.
    # The dev loop's copy goes last, so that index stays at output 0 and inlines
    # the bundle's bootstrap rather than DDC's.
    expected_labels = ["flutter_bootstrap.js", "index.html"]
    if expect_dev_loop_guard:
        expected_labels.append("flutter_bootstrap.js (dev loop)")
    asserts.equals(env, expected_labels, [f["label"] for f in files])
    bootstrap, index = files[0], files[1]
    asserts.equals(env, 0, index["builtins"]["flutter_bootstrap_js"]["from_output"])

    # Without a build config the loader has nothing to boot, and it is the one
    # built-in that cannot come from anywhere but this rule.
    for entry in [bootstrap, index]:
        asserts.true(
            env,
            "_flutter.buildConfig" in entry["builtins"]["flutter_build_config"]["value"],
            "%s must receive this target's build config" % entry["label"],
        )

    # The guard exists because the dev tool serves index.html as built while
    # serving a DDC-configured bootstrap beside it. It is a debug-only concern,
    # and turning it on in release would refuse a legitimate single-file
    # deployment.
    asserts.equals(env, expect_dev_loop_guard, index["dev_loop_guard"])
    asserts.false(
        env,
        bootstrap["dev_loop_guard"],
        "the guard is about index.html; a bootstrap is served by the dev loop, not inlined",
    )

    # The dev loop's bootstrap: the same template, the same defines, DDC's
    # build config. Without this the run served a bootstrap the dev tool wrote
    # from string literals, which no `bootstrap_js` template and no
    # `web_defines` entry could reach.
    if expect_dev_loop_guard:
        dev = files[2]
        asserts.equals(
            env,
            bootstrap["template"],
            dev["template"],
            "the dev loop must boot from the same template the bundle ships",
        )
        dev_config = dev["builtins"]["flutter_build_config"]["value"]
        asserts.true(
            env,
            "\"compileTarget\":\"dartdevc\"" in dev_config,
            "the dev loop compiles with DDC, so its build config must say so: %s" % dev_config,
        )
        asserts.true(
            env,
            "\"useLocalCanvasKit\":true" in dev_config,
            "the dev loop serves the renderer from the bundle it is serving: %s" % dev_config,
        )
        asserts.false(
            env,
            "\"compileTarget\":\"dartdevc\"" in bootstrap["builtins"]["flutter_build_config"]["value"],
            "the bundle's own bootstrap must name the bundle's compiler, not DDC's",
        )

        # A worker registered against localhost outlives the run and serves the
        # next one a stale bundle. Upstream's run mode substitutes null too.
        asserts.equals(env, "null", dev["builtins"]["flutter_service_worker_version"]["value"])

        # One template, read twice: a deprecated construct in it is one
        # mistake, and reporting it once is the difference between a clear
        # error and a doubled one.
        asserts.true(env, bootstrap["check_constructs"])
        asserts.true(env, index["check_constructs"])
        asserts.false(env, dev["check_constructs"])

    # Upstream substitutes an empty base href into the bootstrap and the real
    # one into index.html.
    asserts.equals(env, "", bootstrap["base_href"])
    asserts.equals(env, "/", index["base_href"])

    # Named from the target under test rather than written down, so the same
    # assertion serves every fixture instead of pinning one fixture's name.
    prefix = analysistest.target_under_test(env).label.name
    outputs = _template_action_outputs(env)
    for expected in [prefix + "_index.html", prefix + "_flutter_bootstrap.js"]:
        asserts.true(env, expected in outputs, "%s not declared: %s" % (expected, outputs))

    # The dev loop's bootstrap is declared only where there is a dev loop: it
    # names DDC output a release bundle does not contain.
    asserts.equals(
        env,
        expect_dev_loop_guard,
        prefix + "_dev_flutter_bootstrap.js" in outputs,
        "the dev bootstrap belongs to debug builds only: %s" % outputs,
    )

    # And the bundler is told to ship them under the names the page asks for.
    bundle = written_json(env, "_web_bundle_config.json")
    if bundle != None:
        dsts = [c["dst"] for c in bundle["copies"]]
        for expected in ["index.html", "flutter_bootstrap.js"]:
            asserts.true(env, expected in dsts, "%s missing from bundle: %s" % (expected, dsts))

# -- Reserved bundle destinations --------------------------------------------
#
# These live in their own package because the destination a `web_assets` entry
# takes is its path relative to the *bundle's* package, with a leading `web/`
# stripped. Only a fixture sitting beside its own `web/` directory produces the
# collisions under test.

def _reserved_file_collision_test_impl(ctx):
    """A web asset landing on a generated file is refused, by name."""
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, "would be bundled as \"version.json\"")

    # The message has to carry the way out, or it just tells the user to delete
    # their file.
    asserts.expect_failure(env, "`version_json`")
    return analysistest.end(env)

_reserved_file_collision_test = analysistest.make(
    _reserved_file_collision_test_impl,
    expect_failure = True,
)

def _reserved_dir_collision_test_impl(ctx):
    """A web asset landing inside a generated directory is refused too.

    `canvaskit/` is filled file by file from the web SDK, so a user file there
    would replace one renderer artifact and leave the rest — a mismatch against
    the engine revision the app was compiled against, which surfaces as a blank
    page nowhere near its cause.
    """
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, "canvaskit/canvaskit.js")
    asserts.expect_failure(env, "engine revision")
    return analysistest.end(env)

_reserved_dir_collision_test = analysistest.make(
    _reserved_dir_collision_test_impl,
    expect_failure = True,
)

def _reserved_allows_ordinary_asset_test_impl(ctx):
    """The check must not refuse the assets `web/` exists to carry.

    Without this, a check that failed on everything would satisfy both tests
    above.
    """
    env = analysistest.begin(ctx)
    configs = [
        a
        for a in analysistest.target_actions(env)
        if a.mnemonic == "FileWrite" and
           a.outputs.to_list()[0].basename.endswith("_web_bundle_config.json")
    ]
    asserts.equals(env, 1, len(configs), "expected exactly one bundle config write")
    if configs:
        asserts.true(
            env,
            "\"favicon.png\"" in configs[0].content,
            "the favicon must still reach the bundle: %s" % configs[0].content,
        )
    return analysistest.end(env)

_reserved_allows_ordinary_asset_test = analysistest.make(
    _reserved_allows_ordinary_asset_test_impl,
)

def _own_service_worker_test_impl(ctx):
    """`pwa = False` hands the name over, and the user's file is what ships.

    The paired failure test below is what makes this one mean something: the
    check has to distinguish the two states rather than allow or refuse both.
    """
    env = analysistest.begin(ctx)

    # No generated worker to collide with.
    writes = [
        a
        for a in analysistest.target_actions(env)
        if a.mnemonic == "FileWrite" and
           a.outputs.to_list()[0].basename.endswith("_flutter_service_worker.js")
    ]
    asserts.equals(env, [], writes, "pwa = False must generate no worker")

    configs = [
        a
        for a in analysistest.target_actions(env)
        if a.mnemonic == "FileWrite" and
           a.outputs.to_list()[0].basename.endswith("_web_bundle_config.json")
    ]
    if configs:
        copies = json.decode(configs[0].content)["copies"]
        srcs = [c["src"] for c in copies if c["dst"] == "flutter_service_worker.js"]
        asserts.equals(env, 1, len(srcs), "exactly one file may claim the worker's name")
        if srcs:
            asserts.true(
                env,
                srcs[0].endswith("web_reserved/web/flutter_service_worker.js"),
                "the shipped worker must be the user's, got %s" % srcs[0],
            )
    return analysistest.end(env)

_own_service_worker_test = analysistest.make(_own_service_worker_test_impl)

def _own_service_worker_collision_test_impl(ctx):
    """With the rule shipping a worker too, the same file is refused."""
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, "flutter_service_worker.js")
    asserts.expect_failure(env, "pwa = False")
    return analysistest.end(env)

_own_service_worker_collision_test = analysistest.make(
    _own_service_worker_collision_test_impl,
    expect_failure = True,
)

def web_reserved_test_suite(name):
    """Fixtures and tests for the reserved-destination check.

    Instantiated from `flutter/tests/web_reserved/BUILD.bazel` so the fixtures
    sit beside their own `web/` directory.

    Args:
        name: Prefix for the generated test targets.
    """
    flutter_web_bundle(
        name = "_version_collision",
        package_name = "web_reserved",
        main = "main.dart",
        web_assets = ["web/version.json"],
        tags = ["manual"],
    )
    flutter_web_bundle(
        name = "_canvaskit_collision",
        package_name = "web_reserved",
        main = "main.dart",
        web_assets = ["web/canvaskit/canvaskit.js"],
        tags = ["manual"],
    )

    # The documented way to ship your own worker: `pwa = False` stops the rule
    # generating one, so the name is free.
    flutter_web_bundle(
        name = "_own_worker",
        package_name = "web_reserved",
        main = "main.dart",
        pwa = False,
        web_assets = ["web/flutter_service_worker.js"],
        tags = ["manual"],
    )

    # The same file with the rule still shipping a worker: two files, one name.
    flutter_web_bundle(
        name = "_own_worker_collides",
        package_name = "web_reserved",
        main = "main.dart",
        web_assets = ["web/flutter_service_worker.js"],
        tags = ["manual"],
    )
    flutter_web_bundle(
        name = "_ordinary_asset",
        package_name = "web_reserved",
        main = "main.dart",
        web_assets = ["web/favicon.png"],
        tags = ["manual"],
    )

    _reserved_file_collision_test(
        name = name + "_version_json",
        target_under_test = ":_version_collision",
    )
    _reserved_dir_collision_test(
        name = name + "_canvaskit",
        target_under_test = ":_canvaskit_collision",
    )
    _reserved_allows_ordinary_asset_test(
        name = name + "_ordinary_asset",
        target_under_test = ":_ordinary_asset",
    )
    _own_service_worker_test(
        name = name + "_own_service_worker",
        target_under_test = ":_own_worker",
    )
    _own_service_worker_collision_test(
        name = name + "_own_service_worker_collision",
        target_under_test = ":_own_worker_collides",
    )

def _setup_web_fixtures():
    """flutter_web_bundle instances the analysis tests read.

    `tags = ["manual"]` keeps them out of `bazel test //...` glob expansion;
    the map fixture is additionally built for real by a build_test, which is
    what proves dart2wasm writes main.dart.wasm.map where it was declared
    (an undeclared or misplaced output fails that action, not an assertion).

    Every fixture's `main` sits under this package's own `lib/`, the shape a
    real app has, so the build_tests below cover a nested-package web compile.
    `_web_pkg_root_main_fixture` is the one deliberate exception.
    """
    flutter_web_bundle(
        name = "_web_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        defines = ["from.attr=1"],
        tags = ["manual"],
    )

    # A `main` beside the package's `lib/` rather than inside it, which has no
    # `package:` URI at all. The dev loop's synthetic entrypoint can only
    # import the app by package URI, so a `-c dbg` build of this shape has to
    # stop; `_no_package_uri_refused_test` pins that it does.
    flutter_web_bundle(
        name = "_web_pkg_root_main_fixture",
        package_name = "web_fixture",
        main = "web_fixture_main.dart",
        tags = ["manual"],
    )
    flutter_web_bundle(
        name = "_web_map_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        source_maps = True,
        tags = ["manual"],
    )

    # Read from a `-c dbg` configuration, so the attr is what makes it a
    # profile build rather than the compilation mode agreeing by accident.
    flutter_web_bundle(
        name = "_web_profile_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        profile = True,
        tags = ["manual"],
    )

    # Opposite overrides on the two compilers, so neither can be satisfied by
    # an implementation that resolves one value and passes it to both.
    flutter_web_bundle(
        name = "_web_minify_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        minify_js = "true",
        minify_wasm = "false",
        tags = ["manual"],
    )

    # The dart2js-only flags, all on at once.
    flutter_web_bundle(
        name = "_web_js_flags_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        frequency_based_minification = False,
        native_null_assertions = False,
        tags = ["manual"],
    )

    # `test-experiment` is the SDK's own no-op experiment, declared for
    # exactly this: it exercises the flag path without pinning the fixture to
    # a language feature whose name changes when it ships.
    flutter_web_bundle(
        name = "_web_experiments_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        enable_experiments = ["test-experiment"],
        tags = ["manual"],
    )

    flutter_web_bundle(
        name = "_web_dump_info_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        dump_info = True,
        tags = ["manual"],
    )

    # The same attr in JS-only mode. The tree the report is lifted out of is a
    # different target there (`_dart2js` rather than `_dart2js_fallback`), so
    # a path built from the wrong one fails only here.
    flutter_web_bundle(
        name = "_web_dump_info_js_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        compiler = "dart2js",
        dump_info = True,
        renderer = "canvaskit",
        tags = ["manual"],
    )

    # Both dev-config-carried settings, away from their defaults.
    flutter_web_bundle(
        name = "_web_dev_overrides_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        enable_experiments = ["test-experiment"],
        native_null_assertions = False,
        tags = ["manual"],
    )

    # Release is the only mode that would have stripped, so it is the only
    # one where turning the attr off can be told apart from the gate.
    flutter_web_bundle(
        name = "_web_no_strip_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        strip_wasm = False,
        tags = ["manual"],
    )

    # Wasm-only settings on a target that runs no wasm compile.
    flutter_web_bundle(
        name = "_web_strip_wasm_on_js",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        compiler = "dart2js",
        renderer = "canvaskit",
        strip_wasm = False,
        tags = ["manual"],
    )
    flutter_web_bundle(
        name = "_web_minify_wasm_on_js",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        compiler = "dart2js",
        minify_wasm = "false",
        renderer = "canvaskit",
        tags = ["manual"],
    )

    # One compiler overridden and the other left alone, so a value that
    # reached both would fail on the one that was not asked.
    flutter_web_bundle(
        name = "_web_optimization_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        optimization_level_js = "3",
        tags = ["manual"],
    )

    # `"0"` on both, which is the value the old `if level > 0` guard dropped.
    flutter_web_bundle(
        name = "_web_optimization_zero_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        optimization_level_js = "0",
        optimization_level_wasm = "0",
        tags = ["manual"],
    )

    # A dart2js-only target that sets the dart2js settings, so the call site
    # that serves `compiler = "dart2js"` is pinned rather than only the
    # fallback call inside a dart2wasm target.
    flutter_web_bundle(
        name = "_web_js_only_settings_fixture",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        compiler = "dart2js",
        minify_js = "false",
        optimization_level_js = "3",
        renderer = "canvaskit",
        tags = ["manual"],
    )

    flutter_web_bundle(
        name = "_web_optimization_wasm_on_js",
        package_name = "web_fixture",
        main = "lib/web_fixture_main.dart",
        compiler = "dart2js",
        optimization_level_wasm = "0",
        renderer = "canvaskit",
        tags = ["manual"],
    )

def web_test_suite(name):
    """Instantiate the web-bundle fixtures and the analysis tests over them.

    Args:
        name: Prefix for the generated test targets and the suite itself.
    """
    _setup_web_fixtures()

    _dbg_web_defines_test(
        name = name + "_dbg_defines",
        target_under_test = ":_web_fixture",
    )
    _opt_web_defines_test(
        name = name + "_opt_defines",
        target_under_test = ":_web_fixture",
    )
    _profile_web_defines_test(
        name = name + "_profile_defines",
        target_under_test = ":_web_profile_fixture",
    )

    # The entrypoint names the file this target actually compiles. It used to
    # be asserted as `package:web_fixture/main.dart` — a library this package
    # does not contain, which the app record then resolved to the *workspace
    # root's* `lib/main.dart`. The expectation pinned the defect.
    _dev_config_test(
        name = name + "_dev_config",
        target_under_test = ":_web_fixture",
        expect_entrypoint = "package:web_fixture/web_fixture_main.dart",
    )
    _no_package_uri_refused_test(
        name = name + "_no_package_uri_refused",
        target_under_test = ":_web_pkg_root_main_fixture",
    )
    _wasm_source_map_test(
        name = name + "_wasm_source_map",
        target_under_test = ":_web_map_fixture",
    )
    _wasm_no_source_map_test(
        name = name + "_wasm_no_source_map",
        target_under_test = ":_web_fixture",
    )
    _minify_override_test(
        name = name + "_minify_override",
        target_under_test = ":_web_minify_fixture",
    )
    _wasm_only_attr_refused_test(
        name = name + "_minify_wasm_on_js_refused",
        target_under_test = ":_web_minify_wasm_on_js",
    )
    _optimization_override_test(
        name = name + "_optimization_override",
        target_under_test = ":_web_optimization_fixture",
    )
    _optimization_zero_test(
        name = name + "_optimization_zero",
        target_under_test = ":_web_optimization_zero_fixture",
    )
    _optimization_wasm_on_js_refused_test(
        name = name + "_optimization_wasm_on_js_refused",
        target_under_test = ":_web_optimization_wasm_on_js",
    )
    _js_only_settings_test(
        name = name + "_js_only_settings",
        target_under_test = ":_web_js_only_settings_fixture",
    )

    # Analysis proves the level reaches the command line; only a build proves
    # the compilers accept the ends of the range. `-O0` is the one the old
    # guard never emitted, so it had never been run.
    build_test(
        name = name + "_optimization_zero_build",
        targets = [":_web_optimization_zero_fixture"],
    )
    _js_flags_test(
        name = name + "_js_flags",
        target_under_test = ":_web_js_flags_fixture",
        expect_js = ["--no-frequency-based-minification"],
        # The one flag here that is on by default, so turning it off is the
        # only way to tell the attr from the default.
        expect_not_js = ["native-null-assertions"],
        expect_not_wasm = ["frequency-based", "native-null-assertions"],
    )
    build_test(
        name = name + "_js_flags_build",
        targets = [":_web_js_flags_fixture"],
    )

    # Built in the default (release) configuration, where the icon tree-shake
    # kernel compile runs — so this is what proves the frontend_server takes
    # the flag, not just the two compilers.
    build_test(
        name = name + "_experiments_build",
        targets = [":_web_experiments_fixture"],
    )
    _experiments_test(
        name = name + "_experiments",
        target_under_test = ":_web_experiments_fixture",
    )
    _dev_config_overrides_test(
        name = name + "_dev_config_overrides",
        target_under_test = ":_web_dev_overrides_fixture",
    )
    _dump_info_test(
        name = name + "_dump_info",
        target_under_test = ":_web_dump_info_fixture",
    )
    _dump_info_test(
        name = name + "_dump_info_js_only",
        target_under_test = ":_web_dump_info_js_fixture",
    )
    build_test(
        name = name + "_dump_info_build",
        targets = [
            ":_web_dump_info_fixture",
            ":_web_dump_info_js_fixture",
        ],
    )
    _no_dump_info_test(
        name = name + "_no_dump_info",
        target_under_test = ":_web_fixture",
    )
    _no_strip_release_test(
        name = name + "_no_strip_release",
        target_under_test = ":_web_no_strip_fixture",
    )
    _strip_wasm_on_js_refused_test(
        name = name + "_strip_wasm_on_js_refused",
        target_under_test = ":_web_strip_wasm_on_js",
    )
    build_test(
        name = name + "_wasm_map_build",
        targets = [":_web_map_fixture"],
    )

    # Analysis proves the flags are on the command line; only a real build
    # proves both compilers accept them. `--delete-tostring-package-uri` is
    # dart2wasm-only, so a copy of it onto the dart2js fallback would fail
    # here and nowhere else.
    build_test(
        name = name + "_profile_build",
        targets = [":_web_profile_fixture"],
    )

    unittest.suite(name, _t0_test, _t1_test, _t2_test, _t3_test, _t4_test)
